In [5]:
!pip install ollama
!pip install fitz
!pip install frontend
!pip install PyMuPDF
!pip install pyreadr
!pip install openpyxl
!pip install qwen_vl_utils
!pip install pillow
!pip install torch
!pip install torchvision
#!pip install tabula-py
#!pip install jpype1
!pip install pdfplumber
#!pip install camelot-py

Requirement already satisfied: ollama in /opt/conda/lib/python3.12/site-packages (0.6.0)
Requirement already satisfied: httpx>=0.27 in /opt/conda/lib/python3.12/site-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in /opt/conda/lib/python3.12/site-packages (from ollama) (2.10.6)
Requirement already satisfied: anyio in /opt/conda/lib/python3.12/site-packages (from httpx>=0.27->ollama) (4.8.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.12/site-packages (from httpx>=0.27->ollama) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.12/site-packages (from httpx>=0.27->ollama) (1.0.7)
Requirement already satisfied: idna in /opt/conda/lib/python3.12/site-packages (from httpx>=0.27->ollama) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/conda/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /opt/conda/lib/python3.12/site-packages (from pydantic>=2.9->ollama) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/conda/lib/python3.12/site-packages (from pydantic>=2.9->ollama) (4.12.2)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.12/site-packages (from anyio->httpx>=0.27->ollama) (1.3.1)
Requirement already satisfied: fitz in /opt/conda/lib/python3.12/site-packages (0.0.1.dev2)
Requirement already satisfied: configobj in /opt/conda/lib/python3.12/site-packages (from fitz) (5.0.9)
Requirement already satisfied: configparser in /opt/conda/lib/python3.12/site-packages (from fitz) (7.2.0)
Requirement already satisfied: httplib2 in /opt/conda/lib/python3.12/site-packages (from fitz) (0.31.0)
Requirement already satisfied: nibabel in /opt/conda/lib/python3.12/site-packages (from fitz) (5.3.2)
Requirement already satisfied: nipype in /opt/conda/lib/python3.12/site-packages (from fitz) (1.10.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.12/site-packages (from fitz) (1.26.4)
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (from fitz) (2.2.3)
Requirement already satisfied: pyxnat in /opt/conda/lib/python3.12/site-packages (from fitz) (1.6.4)
Requirement already satisfied: scipy in /opt/conda/lib/python3.12/site-packages (from fitz) (1.15.1)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /opt/conda/lib/python3.12/site-packages (from httplib2->fitz) (3.2.1)
Requirement already satisfied: packaging>=20 in /opt/conda/lib/python3.12/site-packages (from nibabel->fitz) (24.2)
Requirement already satisfied: typing-extensions>=4.6 in /opt/conda/lib/python3.12/site-packages (from nibabel->fitz) (4.12.2)
Requirement already satisfied: click>=6.6.0 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (8.1.8)
Requirement already satisfied: networkx>=2.5 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (3.4.2)
Requirement already satisfied: prov>=1.5.2 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (2.1.1)
Requirement already satisfied: pydot>=1.2.3 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (4.0.1)
Requirement already satisfied: python-dateutil>=2.2 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (2.9.0.post0)
Requirement already satisfied: rdflib>=5.0.0 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (7.4.0)
Requirement already satisfied: simplejson>=3.8.0 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (3.20.2)
Requirement already satisfied: traits>=6.2 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (7.0.2)
Requirement already satisfied: filelock>=3.0.0 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (3.17.0)
Requirement already satisfied: acres in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (0.5.0)
Requirement already satisfied: etelemetry>=0.3.1 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (0.3.1)
Requirement already satisfied: looseversion!=1.2 in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (1.3.0)
Requirement already satisfied: puremagic in /opt/conda/lib/python3.12/site-packages (from nipype->fitz) (1.30)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas->fitz) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas->fitz) (2025.1)
Requirement already satisfied: lxml>=4.3 in /opt/conda/lib/python3.12/site-packages (from pyxnat->fitz) (6.0.2)
Requirement already satisfied: requests>=2.20 in /opt/conda/lib/python3.12/site-packages (from pyxnat->fitz) (2.32.3)
Requirement already satisfied: pathlib>=1.0 in /opt/conda/lib/python3.12/site-packages (from pyxnat->fitz) (1.0.1)
Requirement already satisfied: ci-info>=0.2 in /opt/conda/lib/python3.12/site-packages (from etelemetry>=0.3.1->nipype->fitz) (0.3.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.2->nipype->fitz) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests>=2.20->pyxnat->fitz) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests>=2.20->pyxnat->fitz) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests>=2.20->pyxnat->fitz) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests>=2.20->pyxnat->fitz) (2024.12.14)
Requirement already satisfied: frontend in /opt/conda/lib/python3.12/site-packages (0.0.3)
Requirement already satisfied: starlette>=0.12.0 in /opt/conda/lib/python3.12/site-packages (from frontend) (0.50.0)
Requirement already satisfied: uvicorn>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from frontend) (0.38.0)
Requirement already satisfied: itsdangerous>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from frontend) (2.2.0)
Requirement already satisfied: aiofiles in /opt/conda/lib/python3.12/site-packages (from frontend) (25.1.0)
Requirement already satisfied: anyio<5,>=3.6.2 in /opt/conda/lib/python3.12/site-packages (from starlette>=0.12.0->frontend) (4.8.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.12/site-packages (from starlette>=0.12.0->frontend) (4.12.2)
Requirement already satisfied: click>=7.0 in /opt/conda/lib/python3.12/site-packages (from uvicorn>=0.7.1->frontend) (8.1.8)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.12/site-packages (from uvicorn>=0.7.1->frontend) (0.14.0)
Requirement already satisfied: idna>=2.8 in /opt/conda/lib/python3.12/site-packages (from anyio<5,>=3.6.2->starlette>=0.12.0->frontend) (3.10)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.12/site-packages (from anyio<5,>=3.6.2->starlette>=0.12.0->frontend) (1.3.1)
Collecting PyMuPDF
  Downloading pymupdf-1.26.6-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.26.6-cp310-abi3-manylinux_2_28_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 78.1 MB/s eta 0:00:00a 0:00:01
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.26.6
Requirement already satisfied: pyreadr in /opt/conda/lib/python3.12/site-packages (0.5.3)
Requirement already satisfied: pandas>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from pyreadr) (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadr) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadr) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadr) (2025.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadr) (1.17.0)
Requirement already satisfied: openpyxl in /opt/conda/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: qwen_vl_utils in /opt/conda/lib/python3.12/site-packages (0.0.14)
Requirement already satisfied: av in /opt/conda/lib/python3.12/site-packages (from qwen_vl_utils) (16.0.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from qwen_vl_utils) (24.2)
Requirement already satisfied: pillow in /opt/conda/lib/python3.12/site-packages (from qwen_vl_utils) (11.1.0)
Requirement already satisfied: requests in /opt/conda/lib/python3.12/site-packages (from qwen_vl_utils) (2.32.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests->qwen_vl_utils) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests->qwen_vl_utils) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests->qwen_vl_utils) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests->qwen_vl_utils) (2024.12.14)
Requirement already satisfied: pillow in /opt/conda/lib/python3.12/site-packages (11.1.0)
Requirement already satisfied: torch in /opt/conda/lib/python3.12/site-packages (2.6.0+cu124)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.12/site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.12/site-packages (from torch) (3.1.5)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.12/site-packages (from torch) (2024.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /opt/conda/lib/python3.12/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /opt/conda/lib/python3.12/site-packages (from torch) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /opt/conda/lib/python3.12/site-packages (from torch) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /opt/conda/lib/python3.12/site-packages (from torch) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /opt/conda/lib/python3.12/site-packages (from torch) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /opt/conda/lib/python3.12/site-packages (from torch) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /opt/conda/lib/python3.12/site-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /opt/conda/lib/python3.12/site-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /opt/conda/lib/python3.12/site-packages (from torch) (3.2.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch) (75.8.0)
Requirement already satisfied: sympy==1.13.1 in /opt/conda/lib/python3.12/site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: torchvision in /opt/conda/lib/python3.12/site-packages (0.21.0+cu124)
Requirement already satisfied: numpy in /opt/conda/lib/python3.12/site-packages (from torchvision) (1.26.4)
Requirement already satisfied: torch==2.6.0 in /opt/conda/lib/python3.12/site-packages (from torchvision) (2.6.0+cu124)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /opt/conda/lib/python3.12/site-packages (from torchvision) (11.1.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (4.12.2)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (3.4.2)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (3.1.5)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (2024.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (3.2.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (75.8.0)
Requirement already satisfied: sympy==1.13.1 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0->torchvision) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy==1.13.1->torch==2.6.0->torchvision) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2->torch==2.6.0->torchvision) (3.0.2)
Requirement already satisfied: pdfplumber in /opt/conda/lib/python3.12/site-packages (0.11.8)
Requirement already satisfied: pdfminer.six==20251107 in /opt/conda/lib/python3.12/site-packages (from pdfplumber) (20251107)
Requirement already satisfied: Pillow>=9.1 in /opt/conda/lib/python3.12/site-packages (from pdfplumber) (11.1.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /opt/conda/lib/python3.12/site-packages (from pdfplumber) (5.0.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from pdfminer.six==20251107->pdfplumber) (3.4.1)
Requirement already satisfied: cryptography>=36.0.0 in /opt/conda/lib/python3.12/site-packages (from pdfminer.six==20251107->pdfplumber) (44.0.0)
Requirement already satisfied: cffi>=1.12 in /opt/conda/lib/python3.12/site-packages (from cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.12/site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.22)

In [281]:
!pip install pdf2image

Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pillow in /opt/conda/lib/python3.12/site-packages (from pdf2image) (11.1.0)
Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Installing collected packages: pdf2image
Successfully installed pdf2image-1.17.0

In [1]:
%cd ../../daan/Chloe-project/

/daan/Chloe-project

In [6]:
import sys
import base64
import os
import requests
import ollama
import fitz  # PyMuPDF
import io
import re
import pandas as pd 
import numpy as np 
import json
import time
import pyreadr
from openpyxl import Workbook, load_workbook
from pathlib import Path
import importlib
import functions
importlib.reload(functions)


SEED = 1

# Show all columns without truncation
pd.set_option("display.max_colwidth", None)  

# If you also want to see all rows/columns
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [7]:
import pdfplumber

study_id = "1835" #"2678"

pdf_path = os.path.join(f"extraction_papers/{study_id}.pdf")

extracted_text = ""
with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if text:  # avoid None for empty pages
            extracted_text += text + "\n\n"  # add spacing between pages

In [5]:
print(extracted_text)

Ecotoxicology and Environmental Safety 292 (2025) 117953
Contents lists available at ScienceDirect
Ecotoxicology and Environmental Safety
journal homepage: www.elsevier.com/locate/ecoenv
Unraveling fishers’ perceptions: Impact of mining on fish yield and
diversity in Mwenga, South Kivu, Eastern Democratic Republic of Congo
Dieudonn ´ e Shukuru Wassoa,b,*, Daud Kassama , Adolphe Kwakanaba Mwezec,
Socrate Kamani Tungidib, Emmanuel Tulinabo Ahanyirweb , Christian Masumbuko Barakab,
Rodrigue Balthazar Basengere Ayagirweb,d
aAfrica Centre of Excellence in Aquaculture and Fisheries, Department of Aquaculture Sciences and Fisheries, Lilongwe University of Agriculture and Natural Resources
(LUANAR), Lilongwe P. O. Box 219, Malawi
bDepartment of Animal Sciences, Evangelical University in Africa, Bukavu P.O. Box 3323, the Democratic Republic of the Congo
cDepartment of Environment and Earth Resources Management, Evangelical University in Africa, Bukavu P.O. Box 3323, the Democratic Republic of the Congo
dDepartment of Environment and Sustainable Development, Institut Sup´erieur de D´eveloppement Rural de Bukavu, Bukavu P.O. Box 1860, the Democratic Republic of the
Congo
A R T I C L E I N F O A B S T R A C T
Keywords: In South Kivu province, Eastern Democratic Republic of Congo, a significant number of active mines are situated
Aquatic resources near strictly protected ecosystems, where adverse effects including deforestation, water pollution, soil degra-
Conservation dation and loss of biodiversity have been documented. Understanding the local communities’ perceptions of how
Subsistence fishing
mining affects fish diversity and yield is crucial for fostering a harmonious relationship among stakeholders and
Indigenous knowledge
preserving the environment and its biodiversity, particularly in Mwenga territory where mining activities are
widespread. This study aimed to establish the typology of fishers, and to investigate their perceptions and drivers
of these perceptions regarding the impact of mining operations on fish yield and diversity in the Mwenga ter-
ritory, Democratic Republic of Congo. A cross-sectional survey involving 75 randomly selected fishers was
conducted, and data were collected through structured questionnaires. Water quality parameters were measured
at three different monitoring sites along the Zalya-Elila River, a primary watercourse in the Mwenga territory.
Principal component analysis identified two distinct groups of fishers. Key factors influencing the diversity of
Mwenga fishers included age, household size, monthly income, fishing experience, number of fish caught daily
15 years ago, distance between the river and the mine site, fishing hours per day, weekly fishing frequency, and
quantity (weight) of fish caught per day currently and 15 years ago (p < 0.05). A significant proportion
(39.02 %) of surveyed fishers reported a decline in fish diversity due to mining activities, with only seven out of
the 13 previously present fish species remaining in the study area. Moreover, the average catch per fisher per day
decreased from 9.00 ±4.20 Kg 15 years ago to 4.45 ±1.88 Kg currently. Various factors influenced fishers’
perceptions, including age, marital status, education level, household size, comparison of current and past fish
catches, presence of nearby mining sites, fishing hours per day, pollution, interconnections between water
bodies, and the sediment presence in water bodies (p <0.05). Among the 11 water parameters monitored, only
the temperature, dissolved oxygen, biological oxygen demand over five days, chlorite concentration, sulfate, and
nitrate met acceptable and desirable ranges for fish in natural ecosystems. The information obtained from this
study constitutes a prerequisite for developing and implementing studies or policies aimed at mitigating and
combatting the negative effects of mining on fish yield and diversity in the Mwenga territory. Actions and
policies are needed from local authorities to ensure the sustainability of fish biodiversity in the Mwenga territory.
1. Introduction Earth and underpins the functioning of ecosystems and the many ad-
vantages that nature provides to people (Brauman et al., 2020). It is
Biodiversity plays a crucial role in supporting and sustaining life on essential to achieving sustainability goals related to food and water
* Correspondence to: Lilongwe P. O. Box 219, Malawi.
E-mail address: wasso.dieudo@gmail.com(D.S. Wasso).
https://doi.org/10.1016/j.ecoenv.2025.117953
Received 30 March 2024; Received in revised form 17 December 2024; Accepted 22 February 2025
Available online 3 March 2025
0147-6513/© 2025 The Authors. Published by Elsevier Inc. This is an open access article under the CC BY license ( http://creativecommons.org/licenses/by/4.0/ ).

D.S. Wasso et al. E c o t o x i c o l o g y a n d E n v i r o n m e n t a l S a f e t y 292 (2025) 117953
security, health and wellbeing, and climate change mitigation and ecosystems to significant risks.
adaptation, among others (Ortiz et al., 2021, Sietz and Neudert, 2022, The impacts of mining are not limited to the environment and human
Moreno Vargas et al., 2023, Newell, 2023). Ranging in organismal levels health, but also include social impacts on neighboring communities,
from genes to species and ecosystems, biodiversity directly or indirectly including the marginalization of host communities, the relocation of
supports the accomplishment of all 17 Sustainable Development Goals communities, the oppression of low-income local citizens, and mining
(SDGs), which are ambitious targets for social and ecological well-being conflicts between mining companies and local communities (Kitula,
that are expected to be met by 2030 (Petersson and Stoett, 2022). The 2006; Conde and Le Billon, 2017). According to Dougherty and Olsen
SDG framework offers a chance to reaffirm that biodiversity benefits (2014), these conflicts often arise from local perceptions of mining’s
human well-being and that, as a vital component of the earth’s life detrimental effects on the natural environment and the communities’
support system, it must be protected in order to maintain sustainability lives in terms of the sources of livelihoods, resource stocks, and inherent
(Fallah Shayan et al., 2022). However, due to human activity, it is dis- traditional lifestyle (Dougherty and Olsen, 2014). For instance, local
appearing globally at unprecedented rates, putting over a million spe- populations in Mongolia resisted mining activities due to water
cies in danger of going extinct (Bellard et al., 2022). contamination and land alteration (Beck et al., 2007, Reeves, 2011,
The Congo Basin is home to the greatest biodiversity on the African Dalaibuyan, 2012), while in the Andean highlands of Peru, residents
continent and is ranked second globally, after the Amazon Basin competed for land and water (Conde and Le Billon, 2017).
(Harrison et al., 2016). In particular, the Democratic Republic of Congo Indigenous peoples around the world have preserved distinctive
(DRC) has a rich array of biodiversity, including many endangered, understandings, based on cultural experience, that direct relationships
endemic, and rare species (Balmford et al., 2001, Demey and Louette, between human and non-human beings in specific ecosystems. These
2001, Mbale et al., 2022), primarily located within its aquatic, forest, understandings and relationships constitute a system referred to as
and savannah ecosystems. The country hosts 450 mammal species, 1150 indigenous knowledge (Bruchac, 2014). Different authors have used
bird species, 400 fish species, and over 15,000 plant species (Debroux various terms to describe indigenous knowledge, depending on how it
et al., 2007). Among these are rare animals such as the northern white has been acquired and applied. Some authors have referred to it as
rhino, mountain gorilla, the endemic okapi, and unique great apes like traditional ecological knowledge or traditional environmental knowl-
the eastern lowland gorilla and bonobo. Endemism is high, with 6 % of edge (TEK), while others have called it indigenous technical knowledge
its mammal species and 10 % of its plant species found exclusively (ITK) (Stevenson, 1996; Usher, 2000). It is the library of knowledge that
within its borders (Debroux et al., 2007). However, this biodiversity people possess of the environments where they live (Vidal, 2019). It
faces significant threats from activities such as mining, deforestation, evolves and adapts in response to changes in policies, practices, species
and hunting (Plumptre et al., 2007, Maldonado et al., 2012, Sosef et al., distribution, targeted species, human migration, climate-driven
2017). ecosystem changes, market demands, and other factors (Ames, 2005;
Mining, while contributing significantly to the DRC’s gross domestic Donda and Manyungwa-Pasani, 2018). Increasing recognition of the
product (GDP) (Dedieu et al., 2015, Allard et al., 2016), is particularly importance of indigenous knowledge has led to calls for its integration
detrimental to the country’s aquatic biodiversity. Mining operations across multiple disciplines, including conservation and biodiversity,
contaminate waterbodies and the surrounding environment with heavy disaster risk reduction, and natural resource management (Mercer et al.,
metals and petrochemicals, including mercury (Hg), arsenic (As), cya- 2010).
nide, and hydrocarbons (Gonzalez et al., 2019, Araújo-Flores et al., Indigenous knowledge is crucial in conserving fish resources and
2021). This pollution severely impacts aquatic life, particularly fish, maintaining genetic diversity, as local fishing communities possess
which are both indicators of environmental health and direct recipients extensive expertise that can be used for relevant information. Several
of these contaminants (Park et al., 2016, Atique et al., 2019). The scientific studies have underscored the importance of local knowledge in
accumulation of toxic metals like Hg and As in fish can lead to reduced identifying fish populations, spawning areas, and managing resource use
reproductive capacity, disrupted enzymatic processes, and compro- and cultural practices (Rim-Ruke et al., 2013; Rocliffe et al., 2020). For
mised immune systems, increasing the risk of population decline among example, in the Western Solomon Islands, Indigenous communities
aquatic species (Kumari et al., 2017, Hussain et al., 2018). identified changes in the population of bumphead parrotfish (Bolbome-
Human health is also at significant risk due to the consumption of topon muricatum) and proposed conservation strategies (Aswani and
contaminated fish, which is a critical protein source globally (Garvey, Hamilton, 2004). In Canada, cod fishers provided valuable insights into
2019, R´e et al., 2021). High levels of Hg in fish have been linked to the movement patterns and population structure of Atlantic cod (Gadus
nuclear damage in human populations (Galeano-Pa´ez et al., 2021, morhua) (Murray et al., 2008). Similarly, in the Brazilian Amazon, local
Co´rdoba-Tovar et al., 2023). For instance, in South Africa, the regular fishers observed changes in fish species abundance following the con-
consumption of Cyprinus carpio, Clarias gariepinus, and Oreochromis struction of a dam (Hallwass et al., 2013). In Zanzibar, (Omar et al.,
mossambicus, which are contaminated with trace elements from inten- 2018) reported that indigenous knowledge played a key role in identi-
sive mining activities, has been associated with both carcinogenic and fying fishery regimes, fish stocks, and determining seasonal fishing
non-carcinogenic health risks (Erasmus et al., 2022). Similarly, Balali-- activities.
Mood et al. (2021)reported that the frequent consumption of contam- Fishers, whose livelihoods depend directly on the services provided
inated fish can lead to dysfunction and damage to the liver, kidneys, and by aquatic ecosystems, are among the most affected by environmental
cardiovascular system, as well as an elevated risk of cancer, particularly disturbances in these ecosystems (Allison and Ellis, 2001, Allison et al.,
of the kidney, liver, thyroid, and bones (Pheiffer et al., 2018; 2012). They are also the most knowledgeable about the nature of such
Balali-Mood et al., 2021; Volschenk et al., 2019). disturbances (Johannes, 2003, Allison et al., 2012). Johannes (2003)
The situation is particularly acute in South Kivu province, Eastern emphasized that fishers possess critical knowledge about species at risk
DRC, where more than a quarter of active mines and exploration sites of extinction, including the timing and location of key life events such as
overlap with or are located within 10 kilometers of strictly protected migration, spawning aggregations, recruitment, nursery areas, and the
ecosystems (Cirimwami et al., 2015). For instance, Nsambu et al. (2020) habitats of rare or endangered species. They can also offer insights into
reported cases of mercury, sulphide, and phosphate pollution in nine how new practices could be introduced within their communities and
rivers draining the Fizi gold panning areas. Similarly, Nkuba (2021) identify human barriers to implementing purely biological resource
observed comparable pollution issues in the Kamituga gold panning management strategies (Johannes, 2003, Wiyono et al., 2018).
areas of South Kivu, highlighting that mercury is being used by miners Furthermore, fishers can provide information on whether their com-
near and within residential areas, as well as within the catchments of munities hold fundamental conservation ethics, which, if present, could
important rivers, thereby exposing both communities and aquatic be studied and used as a basis for local conservation education
2

D.S. Wasso et al. E c o t o x i c o l o g y a n d E n v i r o n m e n t a l S a f e t y 292 (2025) 117953
(Johannes, 2003; Knudsen, 2008). Kivu province, East of the Democratic Republic of Congo (Fig. 1). This
This expertise extends to fishers’ perceptions of the impacts of territory was selected owing to its enormous mineral potential, its
mining on fish yield and diversity. Such perceptions, as part of their important hydrographic network with fishing and fish farming being
indigenous knowledge, are crucial for informing decisions and policies practiced in waterbodies surrounded by mining sites. Mwenga lies be-
related to fish biodiversity management and mitigating the threats tween 200 m (to the East) and 1800 m (Northeast) above sea level. It is
posed by mining (Beaudreau and Levin, 2014). Moreover, their per- located between 28◦25’29’’ E and 30◦2.16’5’’ S and receives an average
ceptions serve as baseline information for motivating and guiding temperature of 23˚ C with a maximum of 37˚ C and a minimum of 21˚ C
research projects on this issue (Gorjestani, 2000, Beaudreau and Levin, (Aruna et al., 2020). Moreover, Mwenga territory experiences a humid
2014). Studies based on community surveys have shown that residents’ tropical climate, receiving high annual rainfall between 1600 and
environmental perceptions are influenced by their socioeconomic pro- 2200 mm, with a relative minimum occurring in June and July during
file and the spatial distribution of their residences. Specifically, “resi- the dry season (Mangambu, 2016, Aruna et al., 2020). From a hydro-
dents living closer to a natural resource are possibly more concerned graphic point of view, Mwenga territory has several rivers including
with its environmental quality” (Brody et al., 2005, Mafumbu et al., Ulindi, Lubyala, Zalya, Elila and many others that form part of the Congo
2022). Based on this literature, this study aims to establish a typology of basin (Aruna et al., 2020). These rivers (tributaries of the Congo River)
fishers based on their socio-economic profiles, fishing methods, and offer opportunities for fishing and farming activities in the area.
equipment used, and to investigate their perceptions and the factors
driving these perceptions regarding the impact of mining operations on
2.2. Study design, sampling and sample size
fish yield and diversity in the Mwenga territory, Democratic Republic of
Congo.
A cross-sectional study was conducted among fishers over a year.
Face-to-face interviews were conducted using a questionnaire (Supple-
2. Materials and methods
mentary file 1) that included questions where respondents selected one
or more options from a predetermined set of responses, as well as a few
2.1. Study area
open-ended questions where respondents provided answers in their own
words. A total of 75 fishers were randomly selected from Wamuzimu
This study was carried out in the Mwenga territory, located in South
(45) and Basile (30) chiefdoms. The selected fishers had at least 10 years
Fig. 1. Map illustrating the hydrographic potential of the study area and location of mining sites.
3

D.S. Wasso et al. E c o t o x i c o l o g y a n d E n v i r o n m e n t a l S a f e t y 292 (2025) 117953
of experience in the fishing activity. This was a way to ensure that they parameters that were not measured in situ, 600ml of water were
can give their perception of the effect of the mining activities on the fish sampled per site (in triplicate) at 15cm depth. The samples were
yield and diversity by comparing the current status to that of 10 years packaged in polyethylene bottles and then transported under cold chain
ago or more, when mining activities were not intense. to the Laboratory of the Natural Sciences Research Centre in Lwiro for
While conducting the survey, water quality parameters were analysis.
collected along the Zalya-Elila River. Zalya-Elila River was selected as Alkalinity was determined by titration with 0.1N hydrochloric acid
the waterbody of reference as it stretches along the Mwenga territory in the presence of methyl orange (colored indicator at 0.5%). The
and crosses many mining sites. Three sampling sites were selected along concentration of chlorite, magnesium and sulfate was determined by
this river, designated as points A, B, and C in Fig. 1. The first site (A) was titrimetry following the procedure by (Matini et al., 2009). Nitrate was
located upstream (area of low mining activity), the second (B) in the determined using a branded spectrophotometer (NIR BK-S430) (Holm
middle (site close to the area of intense mining activity) and the third (C) et al., 2000).
downstream of the river.
2.4. Data analysis
2.3. Data collection
Responses to the survey questionnaire used were transferred from
The data were collected using a questionnaire with several main Kobo Collect to MS Excel 2019 (Microsoft Excel, 2019). The dataset was
sections. These included the respondents’ sociodemographic profile cleaned then analyzed using R software, version 4.1.3 (R Core Team,
(gender, age, marital status, household size, education level, main ac- 2019). Descriptive statistics (Means, standard deviations and fre-
tivity, secondary activity, monthly income, and experience in fishing). quencies) were performed. A structural typology of the respondents was
Another section covered general information on the fishing activity produced by means of a multidimensional factorial analysis (Principal
(location of the fishing site, fishing equipment, fishing methods, dura- Component Analysis) using the ‘FactoMineR’ (Lˆe et al., 2008) and
tion and frequency of fishing, fishing times, and the practice of diverting ‘Factoextra’ (Kassambara, Mundt, 2017) R packages. Following the
water from the Zalya-Elila River for mining activities). Principal Component Analysis, a classification was carried out (hierar-
Additionally, the questionnaire addressed the fishers’ perceptions of chical ascending classification followed by a partitioning of k-means for
the effect of mining on fish yield and diversity. This included listing all the consolidation of the obtained classes). The ’ggplot2’ package was

In [433]:
with open(f"training_set/markdown/{study_id}.md", 'r') as f: 
    markdown_text = f.read()

print(markdown_text)

# Unraveling fishers' perceptions: Impact of mining on fish yield and diversity in Mwenga, South Kivu, Eastern Democratic Republic of Congo
Dieudonné Wasso
Daud Kassam
Adolphe Mweze
Socrate Tungidi
Emmanuel Ahanyirwe
Christian Baraka
Rodrigue Ayagirwe

Africa Centre of Excellence in Aquaculture and Fisheries
Department of Aquaculture Sciences and Fisheries
Lilongwe University of Agriculture and Natural Resources (LUANAR)

P. O. Box 219
Lilongwe
Malawi, Department of Animal Sciences
Evangelical University in Africa

P.O. Box 3323
Bukavu
the Democratic Republic of the Congo, Africa Centre of Excellence in Aquaculture and Fisheries
Department of Aquaculture Sciences and Fisheries
Lilongwe University of Agriculture and Natural Resources (LUANAR)

P. O. Box 219
Lilongwe
Malawi, Department of Animal Sciences
Evangelical University in Africa

P.O. Box 3323
Bukavu
the Democratic Republic of the Congo, Department of Animal Sciences
Evangelical University in Africa

P.O. Box 3323
Bukavu
the Democratic Republic of the Congo, Department of Animal Sciences
Evangelical University in Africa

P.O. Box 3323
Bukavu
the Democratic Republic of the Congo

Publishd on March 11, 2025

In South Kivu province, Eastern Democratic Republic of Congo, a significant number of active mines are situated near strictly protected ecosystems, where adverse effects including deforestation, water pollution, soil degradation and loss of biodiversity have been documented. Understanding the local communities' perceptions of how mining affects fish diversity and yield is crucial for fostering a harmonious relationship among stakeholders and preserving the environment and its biodiversity, particularly in Mwenga territory where mining activities are widespread. This study aimed to establish the typology of fishers, and to investigate their perceptions and drivers of these perceptions regarding the impact of mining operations on fish yield and diversity in the Mwenga territory, Democratic Republic of Congo. A cross-sectional survey involving 75 randomly selected fishers was conducted, and data were collected through structured questionnaires. Water quality parameters were measured at three different monitoring sites along the Zalya-Elila River, a primary watercourse in the Mwenga territory. Principal component analysis identified two distinct groups of fishers. Key factors influencing the diversity of Mwenga fishers included age, household size, monthly income, fishing experience, number of fish caught daily 15 years ago, distance between the river and the mine site, fishing hours per day, weekly fishing frequency, and quantity (weight) of fish caught per day currently and 15 years ago (p < 0.05). A significant proportion (39.02 %) of surveyed fishers reported a decline in fish diversity due to mining activities, with only seven out of the 13 previously present fish species remaining in the study area. Moreover, the average catch per fisher per day decreased from 9.00 ± 4.20 Kg 15 years ago to 4.45 ± 1.88 Kg currently. Various factors influenced fishers' perceptions, including age, marital status, education level, household size, comparison of current and past fish catches, presence of nearby mining sites, fishing hours per day, pollution, interconnections between water bodies, and the sediment presence in water bodies (p < 0.05). Among the 11 water parameters monitored, only the temperature, dissolved oxygen, biological oxygen demand over five days, chlorite concentration, sulfate, and nitrate met acceptable and desirable ranges for fish in natural ecosystems. The information obtained from this study constitutes a prerequisite for developing and implementing studies or policies aimed at mitigating and combatting the negative effects of mining on fish yield and diversity in the Mwenga territory. Actions and policies are needed from local authorities to ensure the sustainability of fish biodiversity in the Mwenga territory.

### Introduction
Biodiversity plays a crucial role in supporting and sustaining life on Earth and underpins the functioning of ecosystems and the many advantages that nature provides to people (Brauman et al., 2020). It is essential to achieving sustainability goals related to food and water security, health and wellbeing, and climate change mitigation and adaptation, among others (Ortiz et al., 2021, Sietz and Neudert, 2022, Moreno Vargas et al., 2023, Newell, 2023). Ranging in organismal levels from genes to species and ecosystems, biodiversity directly or indirectly supports the accomplishment of all 17 Sustainable Development Goals (SDGs), which are ambitious targets for social and ecological well-being that are expected to be met by 2030 (Petersson and Stoett, 2022). The SDG framework offers a chance to reaffirm that biodiversity benefits human well-being and that, as a vital component of the earth's life support system, it must be protected in order to maintain sustainability (Fallah Shayan et al., 2022). However, due to human activity, it is disappearing globally at unprecedented rates, putting over a million species in danger of going extinct (Bellard et al., 2022).

The Congo Basin is home to the greatest biodiversity on the African continent and is ranked second globally, after the Amazon Basin (Harrison et al., 2016). In particular, the Democratic Republic of Congo (DRC) has a rich array of biodiversity, including many endangered, endemic, and rare species (Balmford et al., 2001, Demey and Louette, 2001, Mbale et al., 2022), primarily located within its aquatic, forest, and savannah ecosystems. The country hosts 450 mammal species, 1150 bird species, 400 fish species, and over 15,000 plant species (Debroux et al., 2007). Among these are rare animals such as the northern white rhino, mountain gorilla, the endemic okapi, and unique great apes like the eastern lowland gorilla and bonobo. Endemism is high, with 6 % of its mammal species and 10 % of its plant species found exclusively within its borders (Debroux et al., 2007). However, this biodiversity faces significant threats from activities such as mining, deforestation, and hunting (Plumptre et al., 2007, Maldonado et al., 2012, Sosef et al., 2017).

Mining, while contributing significantly to the DRC's gross domestic product (GDP) (Dedieu et al., 2015, Allard et al., 2016), is particularly detrimental to the country's aquatic biodiversity. Mining operations contaminate waterbodies and the surrounding environment with heavy metals and petrochemicals, including mercury (Hg), arsenic (As), cyanide, and hydrocarbons (Gonzalez et al., 2019, Araújo-Flores et al., 2021). This pollution severely impacts aquatic life, particularly fish, which are both indicators of environmental health and direct recipients of these contaminants (Park et al., 2016, Atique et al., 2019). The accumulation of toxic metals like Hg and As in fish can lead to reduced reproductive capacity, disrupted enzymatic processes, and compromised immune systems, increasing the risk of population decline among aquatic species (Kumari et al., 2017, Hussain et al., 2018).

Human health is also at significant risk due to the consumption of contaminated fish, which is a critical protein source globally (Garvey, 2019, Ré et al., 2021). High levels of Hg in fish have been linked to nuclear damage in human populations (Galeano-Páez et al., 2021, Córdoba-Tovar et al., 2023). For instance, in South Africa, the regular consumption of Cyprinus carpio, Clarias gariepinus, and Oreochromis mossambicus, which are contaminated with trace elements from intensive mining activities, has been associated with both carcinogenic and non-carcinogenic health risks (Erasmus et al., 2022). Similarly, Balali--Mood et al. (2021) reported that the frequent consumption of contaminated fish can lead to dysfunction and damage to the liver, kidneys, and cardiovascular system, as well as an elevated risk of cancer, particularly of the kidney, liver, thyroid, and bones (Pheiffer et al., 2018;Balali-Mood et al., 2021;Volschenk et al., 2019).

The situation is particularly acute in South Kivu province, Eastern DRC, where more than a quarter of active mines and exploration sites overlap with or are located within 10 kilometers of strictly protected ecosystems (Cirimwami et al., 2015). For instance, Nsambu et al. (2020) reported cases of mercury, sulphide, and phosphate pollution in nine rivers draining the Fizi gold panning areas. Similarly, Nkuba (2021) observed comparable pollution issues in the Kamituga gold panning areas of South Kivu, highlighting that mercury is being used by miners near and within residential areas, as well as within the catchments of important rivers, thereby exposing both communities and aquatic ecosystems to significant risks.

The impacts of mining are not limited to the environment and human health, but also include social impacts on neighboring communities, including the marginalization of host communities, the relocation of communities, the oppression of low-income local citizens, and mining conflicts between mining companies and local communities (Kitula, 2006;Conde and Le Billon, 2017). According to Dougherty and Olsen (2014), these conflicts often arise from local perceptions of mining's detrimental effects on the natural environment and the communities' lives in terms of the sources of livelihoods, resource stocks, and inherent traditional lifestyle (Dougherty and Olsen, 2014). For instance, local populations in Mongolia resisted mining activities due to water contamination and land alteration (Beck et al., 2007, Reeves, 2011, Dalaibuyan, 2012), while in the Andean highlands of Peru, residents competed for land and water (Conde and Le Billon, 2017).

Indigenous peoples around the world have preserved distinctive understandings, based on cultural experience, that direct relationships between human and non-human beings in specific ecosystems. These understandings and relationships constitute a system referred to as indigenous knowledge (Bruchac, 2014). Different authors have used various terms to describe indigenous knowledge, depending on how it has been acquired and applied. Some authors have referred to it as traditional ecological knowledge or traditional environmental knowledge (TEK), while others have called it indigenous technical knowledge (ITK) (Stevenson, 1996;Usher, 2000). It is the library of knowledge that people possess of the environments where they live (Vidal, 2019). It evolves and adapts in response to changes in policies, practices, species distribution, targeted species, human migration, climate-driven ecosystem changes, market demands, and other factors (Ames, 2005;Donda and Manyungwa-Pasani, 2018). Increasing recognition of the importance of indigenous knowledge has led to calls for its integration across multiple disciplines, including conservation and biodiversity, disaster risk reduction, and natural resource management (Mercer et al., 2010).

Indigenous knowledge is crucial in conserving fish resources and maintaining genetic diversity, as local fishing communities possess extensive expertise that can be used for relevant information. Several scientific studies have underscored the importance of local knowledge in identifying fish populations, spawning areas, and managing resource use and cultural practices (Rim-Ruke et al., 2013;Rocliffe et al., 2020). For example, in the Western Solomon Islands, Indigenous communities identified changes in the population of bumphead parrotfish (Bolbometopon muricatum) and proposed conservation strategies (Aswani and Hamilton, 2004). In Canada, cod fishers provided valuable insights into the movement patterns and population structure of Atlantic cod (Gadus morhua) (Murray et al., 2008). Similarly, in the Brazilian Amazon, local fishers observed changes in fish species abundance following the construction of a dam (Hallwass et al., 2013). In Zanzibar, (Omar et al., 2018) reported that indigenous knowledge played a key role in identifying fishery regimes, fish stocks, and determining seasonal fishing activities.

Fishers, whose livelihoods depend directly on the services provided by aquatic ecosystems, are among the most affected by environmental disturbances in these ecosystems (Allison andEllis, 2001, Allison et al., 2012). They are also the most knowledgeable about the nature of such disturbances (Johannes, 2003, Allison et al., 2012). Johannes (2003) emphasized that fishers possess critical knowledge about species at risk of extinction, including the timing and location of key life events such as migration, spawning aggregations, recruitment, nursery areas, and the habitats of rare or endangered species. They can also offer insights into how new practices could be introduced within their communities and identify human barriers to implementing purely biological resource management strategies (Johannes, 2003, Wiyono et al., 2018). Furthermore, fishers can provide information on whether their communities hold fundamental conservation ethics, which, if present, could be studied and used as a basis for local conservation education (Johannes, 2003;Knudsen, 2008).

This expertise extends to fishers' perceptions of the impacts of mining on fish yield and diversity. Such perceptions, as part of their indigenous knowledge, are crucial for informing decisions and policies related to fish biodiversity management and mitigating the threats posed by mining (Beaudreau and Levin, 2014). Moreover, their perceptions serve as baseline information for motivating and guiding research projects on this issue (Gorjestani, 2000, Beaudreau andLevin, 2014). Studies based on community surveys have shown that residents' environmental perceptions are influenced by their socioeconomic profile and the spatial distribution of their residences. Specifically, "residents living closer to a natural resource are possibly more concerned with its environmental quality" (Brody et al., 2005, Mafumbu et al., 2022). Based on this literature, this study aims to establish a typology of fishers based on their socio-economic profiles, fishing methods, and equipment used, and to investigate their perceptions and the factors driving these perceptions regarding the impact of mining operations on fish yield and diversity in the Mwenga territory, Democratic Republic of Congo.

### Materials and methods
### Study area
This study was carried out in the Mwenga territory, located in South Kivu province, East of the Democratic Republic of Congo (Fig. 1). This territory was selected owing to its enormous mineral potential, its important hydrographic network with fishing and fish farming being practiced in waterbodies surrounded by mining sites. Mwenga lies between 200 m (to the East) and 1800 m (Northeast) above sea level. It is located between 28 • 25'29'' E and 30 • 2.16'5'' S and receives an average temperature of 23 C with a maximum of 37 C and a minimum of 21 C (Aruna et al., 2020). Moreover, Mwenga territory experiences a humid tropical climate, receiving high annual rainfall between 1600 and 2200 mm, with a relative minimum occurring in June and July during the dry season (Mangambu, 2016, Aruna et al., 2020). From a hydrographic point of view, Mwenga territory has several rivers including Ulindi, Lubyala, Zalya, Elila and many others that form part of the Congo basin (Aruna et al., 2020). These rivers (tributaries of the Congo River) offer opportunities for fishing and farming activities in the area.

### Study design, sampling and sample size
A cross-sectional study was conducted among fishers over a year. Face-to-face interviews were conducted using a questionnaire (Supplementary file 1) that included questions where respondents selected one or more options from a predetermined set of responses, as well as a few open-ended questions where respondents provided answers in their own words. A total of 75 fishers were randomly selected from Wamuzimu (45) and Basile (30) chiefdoms. The selected fishers had at least 10 years Fig. 1. Map illustrating the hydrographic potential of the study area and location of mining sites. D.S. Wasso et al. Ecotoxicology and Environmental Safety 292 (2025)

of experience in the fishing activity. This was a way to ensure that they can give their perception of the effect of the mining activities on the fish yield and diversity by comparing the current status to that of 10 years ago or more, when mining activities were not intense. While conducting the survey, water quality parameters were collected along the Zalya-Elila River. Zalya-Elila River was selected as the waterbody of reference as it stretches along the Mwenga territory and crosses many mining sites. Three sampling sites were selected along this river, designated as points A, B, and C in Fig. 1. The first site (A) was located upstream (area of low mining activity), the second (B) in the middle (site close to the area of intense mining activity) and the third (C) downstream of the river.

### Data collection
The data were collected using a questionnaire with several main sections. These included the respondents' sociodemographic profile (gender, age, marital status, household size, education level, main activity, secondary activity, monthly income, and experience in fishing). Another section covered general information on the fishing activity (location of the fishing site, fishing equipment, fishing methods, duration and frequency of fishing, fishing times, and the practice of diverting water from the Zalya-Elila River for mining activities).

Additionally, the questionnaire addressed the fishers' perceptions of the effect of mining on fish yield and diversity. This included listing all species currently found in the waterbody as per the fishers' catches, species caught 15 years ago, reasons for any changes in fish species caught, the part of the waterbody with the highest fish diversity, and comparing current fish catches with those from 15 years ago. The comparison focused on changes in the number of individuals per species, average size per individual, quantity (weight) of fish caught per fisher per day, and the quality (sweetness and perishability) of the caught fish.

The questionnaire also examined water quality and fish consumers' health. This involved evaluating changes in the water's actual color compared to 15 years ago, presence of sediments, changes in the quantity of sediment currently carried, sources of pollution, perceptions of pollution's consequences on fish yield and diversity, impact of mining on water quality, health problems observed by consumers following the consumption of fish from the waterbody, causes of these health problems, and claims made by fish consumers regarding their safety, given the waterbody's proximity to a mining site.

To gather descriptive data on the identified fish, four focus-group discussion workshops were conducted with fishers-two in each chiefdom (Basile and Wamuzimu). Each focus group had between eight and ten participants. Efforts were made to minimize cognitive inputs from outside the participating fishers, aiming to delegate responsibilities to the fishers as much as possible, in line with Pretty (1995). The fishers' commitment was high, with all 36 invited fishers attending the workshops. These fishers were selected based on their extensive fishing experience. The workshops, led by the same moderator, were held in meeting halls.

These data were collected using the KoBo Collect tool (KoBoCollect/ Toolbox is an open-source field data collection tool developed in collaboration with the Harvard Humanitarian Initiative, Brigham and Women's Hospital, and Kweyo, as explained on KoBo's website(www.  koboToolbox.org). It was designed to support field data retrieval by consolidating various functions and equipment such as questionnaires, GPS, cameras, voice recorders, and other devices into a single instrument that can be connected to a smartphone).


In [434]:
# Example usage of pdf_to_images(): 
image_paths = pdf_to_images(study_id)
print(f"Saved {len(image_paths)} images:", image_paths)

Saved 12 images: ['training_set/images/1835_1.png', 'training_set/images/1835_2.png', 'training_set/images/1835_3.png', 'training_set/images/1835_4.png', 'training_set/images/1835_5.png', 'training_set/images/1835_6.png', 'training_set/images/1835_7.png', 'training_set/images/1835_8.png', 'training_set/images/1835_9.png', 'training_set/images/1835_10.png', 'training_set/images/1835_11.png', 'training_set/images/1835_12.png']

In [241]:
# setup ollama client: 

from ollama import Client

ollama = Client(host="http://ollama.runai-shared.svc.cluster.local")

MODEL =  "qwen2.5vl:72b" #"qwen2.5vl:72b" #https://ollama.com/library/qwen2.5vl
MODEL_Lang = "gpt-oss:120b"

In [242]:
#ollama.pull(MODEL)
for progress in ollama.pull(MODEL, stream=True):
    print(progress)

status='pulling manifest' completed=None total=None digest=None
status='pulling ae3823d63bf1' completed=None total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=None total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=None total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=None total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=None total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=None total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=None total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=744734 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=4717056 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=10848768 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=13004142 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=18655959 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=27660934 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=36761640 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=44371210 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=52830208 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=59797770 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=66167582 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=73756672 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=80268992 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=87690944 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=94653824 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=100806336 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=108392128 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=115371712 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=122358848 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=129408704 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=136339136 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=143306112 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=149749120 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=157249216 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=164179648 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=171245248 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=178249408 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=185253568 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=192233152 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=199245504 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=206200192 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=213200256 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=219934400 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=226836160 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=233856704 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=240836288 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=247844544 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=254836416 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=261836480 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=268844736 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=275799744 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=282869440 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=289873600 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=296820736 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=303836864 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=310820544 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=317816512 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=324751040 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=331833024 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=338538176 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=345550848 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=352575488 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=359562944 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=366546304 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=373550784 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=380567232 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=387591872 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=394534272 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=401558912 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=408391040 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=415505792 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=422496704 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=429245952 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=436446720 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=443411520 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=450296896 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=456891456 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=463912320 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=470895680 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=477908352 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=484896128 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=491859328 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=498941312 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=505929088 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=512863616 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=519892352 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=526888320 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=533864128 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=540887808 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=547868352 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=554639360 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=561541120 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=568336384 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=575344640 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=582377472 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=589303168 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=596331904 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=603310848 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=610336128 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=617332416 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=624357056 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=631299776 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=638308032 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=645357248 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=652324544 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=659308224 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=666300096 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=673296064 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=680308416 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=687050432 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=694017728 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=700993216 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=707997376 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=715034304 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=722021760 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=728960064 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=735964864 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=742973120 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=749985472 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=757039104 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=763957248 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=770944704 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=777887424 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=784670720 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=791654400 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=798679040 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=805408768 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=812421120 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=819466240 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=826429440 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=833425408 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=840409088 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=847466496 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=854454272 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=861421568 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=868413440 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'
status='pulling ae3823d63bf1' completed=875388928 total=48709030400 digest='sha256:ae3823d63bf19077ec4c484843defaf89c4494a61d32db9b1e38c9bbd2343cb4'

In [243]:
for progress in ollama.pull(MODEL_Lang, stream=True):
    print(progress)

status='pulling manifest' completed=None total=None digest=None
status='pulling 6be6d66a3f54' completed=None total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=None total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=None total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=None total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=None total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=601598 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=5938052 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=10223691 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=17605264 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=25306281 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=32341520 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=40815691 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=48672320 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=55816729 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=62394240 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=69410688 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=76447616 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=83423104 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=90406784 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=97407488 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=104423936 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=111423680 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=118378368 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=125407424 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=132387008 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=139358400 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=146284736 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=153366400 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=160026496 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=167038848 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=174055616 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=180670656 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=187240640 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=194642112 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=201646272 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=208657984 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=215682944 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=221941952 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=228954304 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=236609728 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=243617024 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=250626240 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=257277504 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=263793354 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=270662080 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=277420480 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=283834816 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=291597056 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=297896704 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=304339712 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=311361216 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=317627776 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=324926848 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=331898240 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=338331776 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=344243584 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=350952832 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=356044160 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=362982784 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=370162752 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=376077056 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=383143296 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=390069632 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=397340032 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=403643776 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=411155840 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=418049408 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=423968128 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=431914368 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=438758144 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=445492608 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=452173184 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=459558272 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=466500992 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=472857984 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=479943744 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=486791936 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=494196544 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=499522624 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=507026496 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=514824960 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=521845504 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=528030464 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=535243520 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=542714944 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=549485632 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=555809856 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=563276864 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=570313792 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=577420032 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=583752448 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=590986304 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=598039616 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=604986432 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=611986816 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=618467008 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=625970880 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=632978496 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=639470976 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=646303104 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=653278912 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=660188864 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=667213504 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=673271488 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=680431296 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=688176512 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=694009216 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=701046144 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=708897856 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=715148352 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=722337152 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=729464192 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=736468352 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=743296064 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=750352832 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=757042240 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=764013952 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=770997632 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=776908160 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=783703424 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=789446016 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=796044992 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=803077824 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=809864896 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=816623296 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=823635968 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=830582784 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=837595136 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=844611584 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=851140608 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=857988800 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=864927424 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=871848704 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'
status='pulling 6be6d66a3f54' completed=878574336 total=65369799840 digest='sha256:6be6d66a3f546d8c19b130dc41dc24b2fc159f84ffbc76a0ee0676205083cf5a'

In [244]:
# list models 
for mod in ollama.list().models:
    print(mod)
    print('\n')

model='gpt-oss:120b' modified_at=datetime.datetime(2025, 12, 7, 8, 5, 53, 188877, tzinfo=TzInfo(UTC)) digest='a951a23b46a1f6093dafee2ea481d634b4e31ac720a8a16f3f91e04f5a40ecd9' size=65369818941 details=ModelDetails(parent_model='', format='gguf', family='gptoss', families=['gptoss'], parameter_size='116.8B', quantization_level='MXFP4')


model='qwen2.5vl:72b' modified_at=datetime.datetime(2025, 12, 7, 7, 55, 17, 870409, tzinfo=TzInfo(UTC)) digest='05ea68274581d182f474987ced445c380fccff8c0f9ef8a9bdb48c4ee2ba9620' size=48709042849 details=ModelDetails(parent_model='', format='gguf', family='qwen25vl', families=['qwen25vl'], parameter_size='73.4B', quantization_level='Q4_K_M')

In [272]:
prompt_format = {
    "type": "object",
    "properties": {
        "scale": {
            "type": "string",
            "enum": ["Local", "Regional", "Global"],
            # "description": (
            #     "Local: The paper focuses on a case study from a single mine.\n"
            #     "Regional: This study focuses on a region of the world. This could be subnational (a series of case studies within an area or a region within a country), "
            #     "national (the country level impact from a single country), multinational (an area that exceeds country bounds), or an area in international waters.\n"
            #     "Global: The study is a global level analysis. "
            # ),
        },
        "country_or_continent": {
            "type": "string",
            # "description": "Which country, countries or continent is this study focused?",
        },
        "specific_location": {
            "type": "string",
            # "description": "Where specifically is the study focused? I.e., Central Africa, Clarion Clipperton Zone, Global, etc.",
        },
        "mined_commodities": {
            "type": "string",
            # "description": (
            #     "List all the commodities studied (e.g., mined) in this paper (this could be one or multiple). List any specific commodities "
            #     "that are being mined or were mined in the past. For example: If the text states that the studied mine is a coal mine, then the commodity is coal. "
            #     "Polymetallic nodules in the CCZ contain: Mn, Cu, Co, Ni."
            # ),
        },
        "mining_stage": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["Mineral occurrences","Exploration/Pre-operational","Operational","Closed","Rehabilitation","NA"]
            },
            "uniqueItems": True,
            # "description": (
            #     "What is the stage of mining? Multiple options may be applicable. "
            #     "Mineral occurrences: Where a known commodity is located, this could be any stage of mining (exploration, operational, closed, etc.). "
            #     "Exploration/Pre-operational: Where a commodity is known to occur, but mining activities have not commenced. "
            #     "Operational: Mining activities are occurring. The mine is active (e.g., production reported). "
            #     "Closed: Mining activities have concluded, the site could be abandoned or rehabilitated/relinquished. "
            #     "Rehabilitation: Treatment or management of land/water disturbed by mining. Mining stage may also be operational and/or closed."                    
            # ),
            "default":[]
        },
        "type_of_mining_activity": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["Open cut","Underground","Mountaintop removal","In-situ leaching","Placer mining","Dredging","Artisanal small-scale mining","Nodule mining","Sulphide mining","Crust mining","Quarrying", "NA"],
            },
            "uniqueItems": True,
            # "description": (
            #     "If this information is not explicitly stated in the study, select NA. Multiple options may be applicable."
            # ),
            "default": []
        },
        "experimental_design": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["Mining area vs non-mining area","Current mining vs post-mining","Pre-mining vs current mining","Pre-mining vs post-mining","Pre-mining vs hypothetical mining", "NA"],
            },
            "uniqueItems": True,
            # "description": (
            #     "What comparison is made in mining conditions to determine biodiversity impacts? "
            #     "Mining area vs non-mining area: The impacts of mining in a mining area (any stage) are compared to an untouched area not used for mining. "
            #     "Current mining vs post-mining: The impacts of mining in an area currently being mined are compared to a different area that has undergone mining in the past. "
            #     "Pre-mining vs current mining: The impacts of current mining activities are compared to the state of biodiversity before mining commenced in the same site/area. "
            #     "Pre-mining vs post-mining: The impacts of mining on biodiversity are compared between an area that has undergone mining (after operations have ceased) and the same area before mining occurred. "
            #     "Pre-mining vs hypothetical mining: A mining area (pre-operation) is compared to a hypothetical current/post-mining scenario. "
            #     "Multiple options may be applicable."
            # ),
            "default":[]
        },
        "taxonomic_groups": {
            "type": "string",
            # "description": (
            #     "Which species group/s are investigated in this study? "
            #     "Please be specific, if possible (i.e., salamanders, skinks), otherwise use broader taxonomic group (i.e., mammals, amphibians, etc.)."
            # ),
        },
        "biomes_of_assessment": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["Marine", "Freshwater", "Grassland", "Savanna", "Shrubland", "Wetlands", "Rocky areas", "Caves and subterranean", "Forest", "Desert", "Tundra", "NA"]
            },
            "uniqueItems": True,
            # "description": (
            #     "Select the biome in which the biodiversity assessment was conducted (multiple options may be applicable). If this information is not explicitly stated in the study, select NA."
            # ),
            "default": []
        },
        "method_of_assessment": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["Spatial modelling","Expert opinion","Statistical analysis","In-situ sampling","Laboratory experiment","Laboratory analysis", "Interviews and questionnaires", "NA"],
            },
            "uniqueItems": True,
            # "description": (
            #     "What method is used to determine the impact or pressure on biodiversity from mining? Multiple options may be applicable. "
            #     "Spatial modelling: A spatial analysis where the mining data is intersected or overlayed with the biodiversity indicator (use of mapping software required for this selection). "
            #     "Expert opinion: The impacts to biodiversity are determined from an expert workshop or from expert judgement. "
            #     "Statistical modelling: Analysis of quantitative data to formulate results. "
            #     "In-situ sampling: Sampling is completed in two or more locations, which can be both inside and outside the impacted area, to compare biodiversity values. "
            #     "Laboratory experiment: Experiments are conducted in a laboratory setting to simulate the impacts of mining on biodiversity. "
            #     "Laboratory analysis: A lab setting is used to assess biodiversity data collected from the field and produce results. "
            #     "Interviews and questionnaires: The biodiversity impacts are determined from questionnaires or interviews with individuals from local communities, through their observations of environmental change."
            # ),
            "default":[]
        },
        "specific_methodology": {
            "type": "string",
            # "description": "Please detail the specific methodology used in the study to quantify the indirect impacts of mining on biodiversity.",
        },
        "temporal_scale": {
            "type": "string",
            "enum": ["1-5", "5-20", "20-50", "50-100", "100-1000", "1000+","NA"],
            # "description": "Over what time period (years) have the impacts to biodiversity been measured? Select 0 if measurements were taken only once. Select NA if no temporal scale is provided.",
        },
        "type_of_impact_or_pressure": {
                "type": "string",
                "enum": ["Pressure","Future impact","Observed impact"],
        },
        "impact_pathway": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["Land/Seabed use","Water depletion","Ecotoxicity","Acidification","Climate change","Eutrophication","NA"],
            },
            "uniqueItems": True,
            "default": []
        },
        "description_of_impact_or_pressure": {
            "type": "string",
        },
        "spatial_scale": {
            "type": "string",
            "enum": ["0-1", "1-5", "5-10", "10-20", "20-50", "50-100", "100+","NA"],
        }
    },
    "required": [
        "scale","country_or_continent","specific_location","mined_commodities","mining_stage","type_of_mining_activity",
        "experimental_design",
        "taxonomic_groups","biomes_of_assessment","method_of_assessment","specific_methodology","temporal_scale", 
        "type_of_impact_or_pressure", "impact_pathway",
        "description_of_impact_or_pressure","spatial_scale"
    ],
    "additionalProperties": False
}


json_format_mines = {
    "type": "object",
    "properties": {
        "mine_names": {
            "type": "array", 
            "items": {"type": "string"},
            "description": (
                "List of mines that are individually assessed in the study. ",
                "To clarify: Each mine listed must be a single mine for which impacts are estimated and presented individually in the paper. ")
        }
    },
    "required": ["mine_names"],
    "additionalProperties": False
}

prompt_format_metrics = {
    "type": "array",
    "description": "List each metric used in the study to measure the impacts of mining.",
    "items": {
        "type": "object",
        "properties": {
            "metric": {
                "type": "string",
                "description": "Metric used in the study to measure the impacts of mining."
            },
            "metric_category": {
                "type": "string",
                "enum": ["Biodiversity metric","(Sub)-organismal metric","Environmental metric"],
                "description": "Metric category."
                }
        },
        "required": [
            "metric", "metric_category"
        ],
        "additionalProperties": False
    }
}


prompt_format_single_metric = {
    "type": "object",
    "properties": {
        "metric": {
            "type": "string",
            "description": "Metric used in the study to measure the impacts of mining."
        },
        "impact_direction": {
            "type": "string",
            "enum": ["No Impact","Increased","Decreased","Changed","Variable","NA"],
            "description": (
                "No Impact: Relative to a reference, mining has caused neither a gain nor loss to biodiversity values (For rehabilitation studies: rehabilitation has increased biodiversity values to be equivalent to reference site/s or pre-mining conditions). "
                "Increased: Relative to a reference, mining is associated with an increase in the metric (For rehabilitation studies: rehabilitation has increased biodiversity values above reference site/s or pre-mining conditions). "
                "Decreased: Relative to a reference, mining is associated with a decrease in the metric (For rehabilitation studies: 1) rehabilitation has increased biodiversity values but not above reference site/s or pre-mining conditions. 2) Rehab has decreased biodiversity values or is having no positive impact). "
                "Changed: The impacts of this metric cannot be measured as increased or decreased but there has been a change when comparing between different conditions. "
                "Variable: The impacts are reported as both increasing biodiversity values in some respects and decreasing them in others. For example, if the paper assesses different species individually and the direction is increased for one species and decreased for another."
            ),
        },
        "significance": {
            "type": "string",
            "enum": ["Significant","Non-significant", "NA"],
            "description": (
                "Is the change in metric stated to be significant (p value < 0.05) or non-significant? Choose NA if this is not stated in the text."
            ),
        },
        "p_value": {
            "type": "string",
            "description": (
                "What is the p-value associated with the metric change? Choose 'NA' if this is not reported in the text."
            ),
        },
        "effect_size": {
            "type": "string",
            "description": (
                "What is the effect size associated with the metric change? Choose 'NA' if this is not reported in the text."
            ),
        }
    },
    "required": [
        "metric", "impact_direction", "significance", "p_value", "effect_size"
    ],
    "additionalProperties": False
}

In [273]:
with open("system_prompt.txt", newline=None) as f:
    system_prompt = f.read()

with open("text_prompt.txt", newline=None) as f:
    text_prompt = f.read()

with open("text_prompt_mine.txt", newline=None) as f:
    text_prompt_mine = f.read()
    
with open("text_prompt_diversity_metrics.txt", newline=None) as f:
    text_prompt_diversity_metrics = f.read()

with open("text_prompt_diversity_metrics_2.txt", newline=None) as f:
    text_prompt_diversity_metrics_2 = f.read()

import importlib
import functions
importlib.reload(functions)

In [72]:
df_full['Study ID'] = df_full['Study ID'].astype(str)
df_test = df_full[df_full['Study ID'].isin(study_test)]
df_test.to_excel("output-test.xlsx", index=False)

In [ ]:
# ----------------------------------------------------------------
# Excel setup

all_cols = ["Scale", "Country/Continent", "Specific location", "Mined commodities", "Mining stage", "Type of mining activity", "Experimental design",
"Taxonomic groups", "Biomes of assessment","Method of assessment","Specific methodology", "Temporal scale", "Type of impact or pressure", 
"Impact pathway", "Description of impact or pressure", "Spatial scale", "Metric", "Metric category", "Impact direction", "Significance", 
"P value", "Effect size", "Response study", "Response metric", "Extracted tables", "Study ID"]

output_file = Path("output-rest_v4.xlsx")
if output_file.exists():
    wb = load_workbook(output_file)
    ws = wb.active
else:
    wb = Workbook()
    ws = wb.active
    ws.append(list(all_cols))
    wb.save(output_file)

In [ ]:
study_train = ["2544","1825","1835","1986","2063","2067","2546","2678","2714","2758"]
study_test = ["1879", "1923", "2032", "2105", "2135", "2298", "2570", "2601", "2643", "2651", "2754", "2846", "2890", "3197", "3436"]
study_rest = ["1829", "1843", "1854", "1859", "1874", "1884", "1885", "1894", "1898", "1926", "1927", "1952", "1960", "1969", "2010", "2016", "2017", "2028", "2049", "2051", "2084", "2095", "2100", "2127", "2139", "2153", "2157", "2165", "2185", "2193", "2229", "2232", "2243", "2244", "2245", "2261", "2271", "2279", "2285", "2289", "2296", "2307", "2308", "2320", "2325", "2327", "2332", "2335", "2337", "2370", "2378", "2381", "2404", "2410", "2433", "2447", "2448", "2452", "2471", "2472", "2483", "2507", "2524", "2530", "2531", "2541", "2550", "2569", "2574", "2581", "2595", "2598", "2602", "2607", "2614", "2616", "2617", "2618", "2621", "2622", "2636", "2637", "2645", "2646", "2649", "2652", "2659", "2668", "2673", "2680", "2681", "2691", "2696", "2703", "2711", "2721", "2724", "2727", "2750", "2760", "2787", "2793", "2823", "2841", "2858", "2869", "2883", "2895", "2909", "2932", "2970", "2997", "3033", "3069", "3082", "3085", "3133", "3170", "3174", "3176", "3247", "3262", "3288"]

len(study_train), len(study_test), len(study_rest)

In [ ]:
import sys
from datetime import datetime

class Logger(object):
    def __init__(self, filename="log.txt"):
        self.terminal = sys.stdout
        self.log = open(filename, "a", encoding="utf-8")

    def write(self, message):
        if message.strip():
            # Define timestamp each time a message is written
            timestamp = datetime.now().strftime("[%Y-%m-%d %H:%M:%S] ")
            message = "".join([timestamp + line for line in message.splitlines(True)])
        self.terminal.write(message)
        self.log.write(message)
        self.log.flush()

    def flush(self):
        pass  # needed for compatibility with sys.stdout

# Redirect print() output
sys.stdout = Logger("log-rest.txt")

In [ ]:
import importlib
import functions
importlib.reload(functions)

# ----------------------------------------------------------------
# Loop through abstracts
start_time = time.time()

i = 0
for study_id in study_rest:  
    print(f"Iteration: {i}\t\t Study: {study_id}")

    image_paths = functions.pdf_to_images(study_id)
    
    extracted_text = ""
    with pdfplumber.open(f"extraction_papers/{study_id}.pdf") as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if text:  # avoid None for empty pages
                extracted_text += text + "\n\n"  # add spacing between pages

    # markdown text extracted with the GROBID model
    with open(f"extraction_papers/{study_id}.md", 'r') as f: 
       markdown_text = f.read()

    # 1. extract tables from the text, to ensure correct interpretation of results 
    print("Extracting tables from the text...")
    text_tables, _ = functions.extract_tables(ollama, MODEL, SEED, system_prompt, extracted_text, image_paths) 
    
    # 2. get names of individual mines, if assessed individually in the study: 
    print("Determining whether multiple mines are assessed individually in the study...") 
    mines_prompt = "Carefully read this mining-impact study:\n\n" + markdown_text + "\n\nRaw text" + extracted_text + "\n\nTables from the text: " + text_tables + """\n\n
    If this mining-impact study individually assessed the impacts of mining of one or more single mines, list each individual mine. 
    Only list single, individual mines, don't list different study locations that assessed the same mine. To clarify: Each listed mine must be one single mine for which 
    impacts are estimated and presented individually in the paper.
    """

    mines, _ = functions.extract_information_formatted(ollama, MODEL, SEED, system_prompt, mines_prompt, json_format_mines, image_paths) 
    #mines_response, _ = functions.extract_information(ollama, MODEL_Lang, SEED, system_prompt, images=False, prompt = mines_prompt)
    #mines = functions.get_json_table(ollama, MODEL_Lang, SEED, mines_response, json_format_mines)
    
    if (mines is None) or (mines=={}) or (mines.get("mine_names", [])==[]) or (len(mines.get("mine_names", []))==1): 
        print("No (multiple) individual mines found, starting extraction for complete study...")
        
        df = functions.get_full_response_json(ollama, 
                                              MODEL, 
                                              MODEL_Lang, 
                                              SEED, 
                                              study_id, 
                                              system_prompt, 
                                              text_prompt, 
                                              text_prompt_diversity_metrics, 
                                              text_prompt_diversity_metrics_2, 
                                              text_tables, 
                                              prompt_format, 
                                              prompt_format_metrics, 
                                              prompt_format_single_metric, 
                                              image_paths, 
                                              extracted_text,
                                              markdown_text
                                       )

        df = df[all_cols] # reorder columns 

        df["P value"] = (
            df["P value"]
            .astype(str)
            .apply(lambda x: re.sub(r"^/(\d)", r"\1", x.strip()))  # remove leading "/" before digits
        )
    
        # append to excel workbook 
        for j, row in enumerate(df.itertuples(index=False), start=1):
            ws.append(row)
            
        print("Done.")
        
    else: 
        print(f"Multiple mines found: {', '.join(mines.get("mine_names"))}")

        for mine in mines.get("mine_names"):
            print(f"Starting extraction for mine: {mine}...")
            
            df = functions.get_full_response_json(ollama, 
                                                  MODEL, 
                                                  MODEL_Lang, 
                                                  SEED, 
                                                  study_id, 
                                                  system_prompt, 
                                                  text_prompt_mine.format(mine=mine), 
                                                  text_prompt_diversity_metrics,
                                                  text_prompt_diversity_metrics_2, 
                                                  text_tables, 
                                                  prompt_format, 
                                                  prompt_format_metrics, 
                                                  prompt_format_single_metric, 
                                                  image_paths, 
                                                  extracted_text,
                                                  markdown_text,
                                                  prompt_prefix = f"For the mine named '{mine}' specifically, do the following:"
                                                 )

            df['Scale'] = "Local" # per definition 
            df = df[all_cols] # reorder columns 

            df["P value"] = (
                df["P value"]
                .astype(str)
                .apply(lambda x: re.sub(r"^/(\d)", r"\1", x.strip()))  # remove leading "/" before digits
            )
    
            # append to excel workbook 
            for j, row in enumerate(df.itertuples(index=False), start=1):
                ws.append(row)
                
            print("Done.")
            
    # make sure all elements are strings 
    #json_table = json_table.map(lambda x: ", ".join(x) if isinstance(x, list) else x)

    wb.save(output_file)
    i+=1

elapsed = time.time() - start_time
print(f"Finished in {elapsed/60:.2f} minutes")

In [ ]:
# Restore normal printing
sys.stdout.log.close()
sys.stdout = sys.stdout.terminal

# Restore the original stdout so print() shows in the notebook again
if hasattr(sys.stdout, "terminal"):
    sys.stdout = sys.stdout.terminal

In [40]:
# Finished in 106.99 minutes

In [ ]:
# ----------------------------------------------------------------
# Excel setup

all_cols = ["Scale", "Country/Continent", "Specific location", "Mined commodities", "Mining stage", "Type of mining activity", "Experimental design",
"Taxonomic groups", "Biomes of assessment","Method of assessment","Specific methodology", "Temporal scale", "Type of impact or pressure", 
"Impact pathway", "Description of impact or pressure", "Spatial scale", "Metric", "Metric category", "Impact direction", "Significance", 
"P value", "Effect size", "Response study", "Response metric", "Extracted tables", "Study ID"]

output_file = Path("output-test_v4.xlsx")
if output_file.exists():
    wb = load_workbook(output_file)
    ws = wb.active
else:
    wb = Workbook()
    ws = wb.active
    ws.append(list(all_cols))
    wb.save(output_file)

# Redirect print() output
sys.stdout = Logger("log-test.txt")

import importlib
import functions
importlib.reload(functions)

# ----------------------------------------------------------------
# Loop through abstracts
start_time = time.time()

i = 0
for study_id in study_test:  
    print(f"Iteration: {i}\t\t Study: {study_id}")

    image_paths = functions.pdf_to_images(study_id)
    
    extracted_text = ""
    with pdfplumber.open(f"extraction_papers/{study_id}.pdf") as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if text:  # avoid None for empty pages
                extracted_text += text + "\n\n"  # add spacing between pages

    # markdown text extracted with the GROBID model
    with open(f"extraction_papers/{study_id}.md", 'r') as f: 
       markdown_text = f.read()

    # 1. extract tables from the text, to ensure correct interpretation of results 
    print("Extracting tables from the text...")
    text_tables, _ = functions.extract_tables(ollama, MODEL, SEED, system_prompt, extracted_text, image_paths) 
    
    # 2. get names of individual mines, if assessed individually in the study: 
    print("Determining whether multiple mines are assessed individually in the study...") 
    mines_prompt = "Carefully read this mining-impact study:\n\n" + markdown_text + "\n\nRaw text" + extracted_text + "\n\nTables from the text: " + text_tables + """\n\n
    If this mining-impact study individually assessed the impacts of mining of one or more single mines, list each individual mine. 
    Only list single, individual mines, don't list different study locations that assessed the same mine. To clarify: Each listed mine must be one single mine for which 
    impacts are estimated and presented individually in the paper.
    """

    mines, _ = functions.extract_information_formatted(ollama, MODEL, SEED, system_prompt, mines_prompt, json_format_mines, image_paths) 
    #mines_response, _ = functions.extract_information(ollama, MODEL_Lang, SEED, system_prompt, images=False, prompt = mines_prompt)
    #mines = functions.get_json_table(ollama, MODEL_Lang, SEED, mines_response, json_format_mines)
    
    if (mines is None) or (mines=={}) or (mines.get("mine_names", [])==[]) or (len(mines.get("mine_names", []))==1): 
        print("No (multiple) individual mines found, starting extraction for complete study...")
        
        df = functions.get_full_response_json(ollama, 
                                              MODEL, 
                                              MODEL_Lang, 
                                              SEED, 
                                              study_id, 
                                              system_prompt, 
                                              text_prompt, 
                                              text_prompt_diversity_metrics, 
                                              text_prompt_diversity_metrics_2, 
                                              text_tables, 
                                              prompt_format, 
                                              prompt_format_metrics, 
                                              prompt_format_single_metric, 
                                              image_paths, 
                                              extracted_text,
                                              markdown_text
                                       )

        df = df[all_cols] # reorder columns 

        df["P value"] = (
            df["P value"]
            .astype(str)
            .apply(lambda x: re.sub(r"^/(\d)", r"\1", x.strip()))  # remove leading "/" before digits
        )
    
        # append to excel workbook 
        for j, row in enumerate(df.itertuples(index=False), start=1):
            ws.append(row)
            
        print("Done.")
        
    else: 
        print(f"Multiple mines found: {', '.join(mines.get("mine_names"))}")

        for mine in mines.get("mine_names"):
            print(f"Starting extraction for mine: {mine}...")
            
            df = functions.get_full_response_json(ollama, 
                                                  MODEL, 
                                                  MODEL_Lang, 
                                                  SEED, 
                                                  study_id, 
                                                  system_prompt, 
                                                  text_prompt_mine.format(mine=mine), 
                                                  text_prompt_diversity_metrics,
                                                  text_prompt_diversity_metrics_2, 
                                                  text_tables, 
                                                  prompt_format, 
                                                  prompt_format_metrics, 
                                                  prompt_format_single_metric, 
                                                  image_paths, 
                                                  extracted_text,
                                                  markdown_text,
                                                  prompt_prefix = f"For the mine named '{mine}' specifically, do the following:"
                                                 )

            df['Scale'] = "Local" # per definition 
            df = df[all_cols] # reorder columns 

            df["P value"] = (
                df["P value"]
                .astype(str)
                .apply(lambda x: re.sub(r"^/(\d)", r"\1", x.strip()))  # remove leading "/" before digits
            )
    
            # append to excel workbook 
            for j, row in enumerate(df.itertuples(index=False), start=1):
                ws.append(row)
                
            print("Done.")
            
    # make sure all elements are strings 
    #json_table = json_table.map(lambda x: ", ".join(x) if isinstance(x, list) else x)

    wb.save(output_file)
    i+=1

elapsed = time.time() - start_time
print(f"Finished in {elapsed/60:.2f} minutes")

# Restore normal printing
sys.stdout.log.close()
sys.stdout = sys.stdout.terminal

# Restore the original stdout so print() shows in the notebook again
if hasattr(sys.stdout, "terminal"):
    sys.stdout = sys.stdout.terminal

In [186]:
import importlib
import functions
importlib.reload(functions)

In [278]:
study_id = "2546"

print(f"Iteration: {i}\t\t Study: {study_id}")

image_paths = functions.pdf_to_images(study_id)

extracted_text = ""
with pdfplumber.open(f"extraction_papers/{study_id}.pdf") as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if text:  # avoid None for empty pages
            extracted_text += text + "\n\n"  # add spacing between pages

# markdown text extracted with the GROBID model
with open(f"extraction_papers/{study_id}.md", 'r') as f: 
    markdown_text = f.read()

# 1. extract tables from the text, to ensure correct interpretation of results 
#print("Extracting tables from the text...")
#text_tables, _ = functions.extract_tables(ollama, MODEL, SEED, system_prompt, extracted_text, image_paths)

Iteration: 2		 Study: 2546

In [188]:
# 2. get text response for the metrics (supply images, text and extracted tables): 
user_prompt_2 = "Carefully read this mining-impact study:\n\n" + markdown_text + "\n\nRaw text: " + extracted_text + "\n\nTables from the text: " + text_tables + "\n\n" + text_prompt_diversity_metrics

response_metrics, messages_metrics = functions.extract_information(ollama, MODEL_Lang, SEED, system_prompt, images=False, prompt = user_prompt_2)    

if response_metrics is None:
    print("Step 2. is None. Trying again...")
    response_metrics, messages_metrics = functions.extract_information(ollama, MODEL_Lang, SEED, system_prompt, images=False, prompt = user_prompt_2)  
    if response_metrics is None: # probable API error or failure to generate 
        print("Failed.") 

json_metrics = functions.get_json_table(ollama, MODEL_Lang, SEED, response_metrics, prompt_format_metrics)
json_metrics

```json
{
  "metrics": [
    {
      "name": "Sediment arsenic concentration (mg/kg)",
      "category": "Environmental metric"
    },
    {
      "name": "Sediment cadmium concentration (mg/kg)",
      "category": "Environmental metric"
    },
    {
      "name": "Sediment lead concentration (mg/kg)",
      "category": "Environmental metric"
    },
    {
      "name": "Sediment zinc concentration (mg/kg)",
      "category": "Environmental metric"
    },
    {
      "name": "Sediment manganese concentration (mg/kg, <0.01)",
      "category": "Environmental metric"
    },
    {
      "name": "Sediment mercury concentration (mg/kg, <0.01)",
      "category": "Environmental metric"
    },
    {
      "name": "Sediment nickel concentration (mg/kg, <0.01)",
      "category": "Environmental metric"
    },
    {
      "name": "Water temperature (°C)",
      "category": "Environmental metric"
    },
    {
      "name": "Water pH",
      "category": "Environmental metric"
    },
    {
      "name": "Dissolved oxygen (mg/L)",
      "category": "Environmental metric"
    },
    {
      "name": "Conductivity (µS or lS)",
      "category": "Environmental metric"
    },
    {
      "name": "Metal concentration in Plecoptera tissue (arsenic, cadmium, lead, zinc, mg/kg)",
      "category": "(Sub)-organismal metric"
    },
    {
      "name": "Shannon H diversity index",
      "category": "Biodiversity metric"
    },
    {
      "name": "Shannon J index",
      "category": "Biodiversity metric"
    },
    {
      "name": "Shannon E evenness index",
      "category": "Biodiversity metric"
    },
    {
      "name": "Percent Ephemeroptera (relative abundance)",
      "category": "Biodiversity metric"
    },
    {
      "name": "Percent Plecoptera (relative abundance)",
      "category": "Biodiversity metric"
    },
    {
      "name": "Percent Trichoptera (relative abundance)",
      "category": "Biodiversity metric"
    },
    {
      "name": "Total number of collected animals (abundance)",
      "category": "Biodiversity metric"
    },
    {
      "name": "Number of families (taxonomic richness)",
      "category": "Biodiversity metric"
    },
    {
      "name": "Number of orders (taxonomic richness)",
      "category": "Biodiversity metric"
    },
    {
      "name": "Species richness (Richness value)",
      "category": "Biodiversity metric"
    },
    {
      "name": "Evenness value (Evenness metric)",
      "category": "Biodiversity metric"
    },
    {
      "name": "Abundance per order (counts of Ephemeroptera, Plecoptera, Trichoptera, Coleoptera, Diptera)",
      "category": "Biodiversity metric"
    }
  ]
}
```

[{'metric': 'Sediment arsenic concentration (mg/kg)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Sediment cadmium concentration (mg/kg)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Sediment lead concentration (mg/kg)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Sediment zinc concentration (mg/kg)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Sediment manganese concentration (mg/kg, <0.01)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Sediment mercury concentration (mg/kg, <0.01)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Sediment nickel concentration (mg/kg, <0.01)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Water temperature (°C)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Water pH', 'metric_category': 'Environmental metric'},
 {'metric': 'Dissolved oxygen (mg/L)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Conductivity (µS or lS)',
  'metric_category': 'Environmental metric'},
 {'metric': 'Metal concentration in Plecoptera tissue (arsenic, cadmium, lead, zinc, mg/kg)',
  'metric_category': '(Sub)-organismal metric'},
 {'metric': 'Shannon H diversity index',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Shannon J index', 'metric_category': 'Biodiversity metric'},
 {'metric': 'Shannon E evenness index',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Percent Ephemeroptera (relative abundance)',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Percent Plecoptera (relative abundance)',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Percent Trichoptera (relative abundance)',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Total number of collected animals (abundance)',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Number of families (taxonomic richness)',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Number of orders (taxonomic richness)',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Species richness (Richness value)',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Evenness value (Evenness metric)',
  'metric_category': 'Biodiversity metric'},
 {'metric': 'Abundance per order (counts of Ephemeroptera, Plecoptera, Trichoptera, Coleoptera, Diptera)',
  'metric_category': 'Biodiversity metric'}]

In [279]:
# 2. get names of individual mines, if assessed individually in the study: 
print("Determining whether multiple mines are assessed individually in the study...") 
mines_prompt = "Carefully read this mining-impact study:\n\n" + markdown_text + "\n\nRaw text" + extracted_text + "\n\nTables from the text: " + text_tables + """\n\n
    If this mining-impact study assessed the impacts of mining of one or more mines individually, list each individual mine. 
    Only list individual mines, don't list study locations that assessed the same mine. To clarify: These are mines for which 
    impacts are estimated and presented individually in the paper. 
    """

mines, _ = functions.extract_information_formatted(ollama, MODEL, SEED, system_prompt, mines_prompt, json_format_mines, image_paths) 
    
print(mines)

Determining whether multiple mines are assessed individually in the study...
{'mine_names': []}

In [180]:
if response_metrics is not None: 
        
    cols = ["Metric", "Metric category", "Impact direction", "Significance", "P value", "Effect size", "Response metric"]
    df = pd.DataFrame([[""] * len(cols)],columns=cols) # empty dataframe
    for metric in response_metrics: 
        df_row = pd.DataFrame([[""] * len(cols)],columns=cols) # empty dataframe
        df_row['Metric'] = metric.get('metric', "")
        df_row['Metric category'] = metric.get('metric_category', "")
        df = pd.concat([df, df_row], ignore_index=True)

    df = df[1:]
    
    for m in df['Metric']: 
        print(f"Extracting information for metric: {m}")
        # setup prompt for metric
        user_prompt_3 = "Carefully read this mining-impact study:\n\n" + markdown_text + "\n\nTables from the text: " + text_tables + "\n\nRaw text" + extracted_text + "\n\n" + f"For the metric {m} specifically, determine:\n" + text_prompt_diversity_metrics_2
        # extract json 
        #response_metric, _ = functions.extract_information_formatted(ollama, MODEL, SEED, system_prompt, user_prompt_3, prompt_format_single_metric, image_paths)
        
        response, messages = functions.extract_information(ollama, MODEL_Lang, SEED, system_prompt, images=False, prompt = user_prompt_3)
        print(response)
        response_metric = functions.get_json_table(ollama, MODEL_Lang, SEED, response, prompt_format_single_metric)
        print(response_metric)
        
        # add to df 
        df.loc[df['Metric'] == m, 'Impact direction'] = response_metric.get("impact_direction", "")
        df.loc[df['Metric'] == m, 'Significance']     = response_metric.get("significance", "")
        df.loc[df['Metric'] == m, 'P value']          = response_metric.get("p_value", "")
        df.loc[df['Metric'] == m, 'Effect size']      = response_metric.get("effect_size", "")
        df.loc[df['Metric'] == m, 'Response metric']  = response # save text response

Extracting information for metric: Shannon H
**Shannon H (diversity index)**

| Item | Answer |
|------|--------|
| **a) Impact direction** | **Decreased** – the study reports that higher cadmium and zinc concentrations are associated with lower Shannon H values (i.e., reduced diversity). |
| **b) Significance** | **significant** – the relationship is reported as statistically significant. |
| **c) P‑value** | **0.017** – given for the MANOVA that includes Shannon H (Wilks’ Λ, F₈,₄₈ = 2.65, P = 0.017). |
| **d) Effect size** | **NA** – no explicit effect‑size metric (e.g., Cohen’s d, η²) is provided for Shannon H. |
{'metric': 'Shannon H', 'impact_direction': 'Decreased', 'significance': 'Significant', 'p_value': '0.017', 'effect_size': 'NA'}
Extracting information for metric: Richness J
**Richness J**

| Item | Answer |
|------|--------|
| a) Impact direction | NA |
| b) Significance | NA |
| c) P‑value | NA |
| d) Effect size | NA |

*Explanation*: The manuscript reports significant relationships between cadmium/zinc and **Shannon H** (diversity) but does not provide any quantitative results, statistical tests, p‑values, or effect‑size estimates for the **Richness J** metric. Consequently, none of the requested information can be extracted.
{'metric': 'Richness\u202fJ', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Evenness E
**Evenness (E) – Mining‑impact summary**

| Item | Answer |
|------|--------|
| **a) Impact direction** | NA (the paper does not give a quantitative statement or clear figure‑based description of whether Evenness increased or decreased as a result of historic mining) |
| **b) Significance** | NA (no statistical test or p‑value for Evenness is reported) |
| **c) P‑value** | NA (not provided) |
| **d) Effect size** | NA (not provided) |

*Explanation*: The manuscript discusses significant relationships between cadmium/zinc and several response variables (total number of organisms, number of families, % Plecoptera, and Shannon H). Although Figure 4 includes a panel for “evenness E,” the text never quantifies the direction of change, its statistical significance, a p‑value, or an effect‑size estimate for this metric. Consequently, all entries are marked **NA**.
{'metric': 'Evenness (E)', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Percent of Ephemeroptera
**Metric:** Percent of Ephemeroptera

| Item | Answer |
|------|--------|
| **a) Impact direction** | NA (the study does not report a directional change in the percentage of Ephemeroptera attributable to historic mining) |
| **b) Significance** | NA (no statistical test or result is presented for this metric) |
| **c) P‑value** | NA (no p‑value is given for a change in % Ephemeroptera) |
| **d) Effect size** | NA (no effect‑size estimate is reported for this metric) |
{'metric': 'Percent of Ephemeroptera', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Percent of Plecoptera
**Metric:** Percent of Plecoptera

| Item | Answer |
|------|--------|
| **a) Impact direction** | **Decrease** – the study reports that higher cadmium and zinc concentrations (the legacy of mining) are associated with a *smaller percentage of Plecoptera* in the stream insect community. |
| **b) Significance** | **significant** – the relationship is described as statistically significant in the MANOVA/step‑wise analyses. |
| **c) P‑value** | **0.017** – the MANOVA that included % Plecoptera yielded *P = 0.017* (also individual tests for cadmium and zinc gave P = 0.017 and P = 0.014, respectively). |
| **d) Effect size** | **NA** – the paper does not provide an explicit effect‑size estimate (e.g., Cohen’s d, η²) for the change in % Plecoptera. |
{'metric': 'Percent of Plecoptera', 'impact_direction': 'Decreased', 'significance': 'Significant', 'p_value': '0.017', 'effect_size': 'NA'}
Extracting information for metric: Percent of Trichoptera
**Metric:** Percent of Trichoptera

| Item | Answer |
|------|--------|
| **a) Impact direction** | NA – the paper does not report a specific change (increase or decrease) in the percentage of Trichoptera associated with mining impact. |
| **b) Significance** | NA – no statistical test or statement of significance is given for this metric. |
| **c) P‑value** | NA – no p‑value is provided for a change in % Trichoptera. |
| **d) Effect size** | NA – the study does not give an effect‑size estimate for this metric. |
{'metric': 'Percent of Trichoptera', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Total number of collected animals
**Metric:** Total number of collected animals

| Item | Answer |
|------|--------|
| **a) Impact direction** | **Decrease** – the study reports that higher cadmium and zinc concentrations are associated with *fewer* total organisms (i.e., a reduction in the total number of collected animals). |
| **b) Significance** | **Significant** – step‑wise MANOVAs showed a statistically significant relationship between metal concentrations (Cd, Zn) and the total number of animals. |
| **c) P‑value** | **Cadmium:** 0.017  **Zinc:** 0.014  (both p‑values are < 0.05, indicating significance) |
| **d) Effect size** | **NA** – no effect‑size metric (e.g., Cohen’s d, η²) is reported for this specific outcome. |
{'metric': 'Total number of collected animals', 'impact_direction': 'Decreased', 'significance': 'Significant', 'p_value': 'Cadmium: 0.017; Zinc: 0.014', 'effect_size': 'NA'}
Extracting information for metric: Number of families
**Metric:** Number of families

| Item | Answer |
|------|--------|
| **a) Impact direction** | **Decrease** – the study reports that higher cadmium and zinc concentrations are associated with *fewer* families (i.e., a reduction in family richness). |
| **b) Significance** | **Significant** – the relationship is reported as statistically significant. |
| **c) P‑value** | **0.017** (overall MANOVA linking cadmium & zinc to number of families; individual tests gave P = 0.017 for cadmium and P = 0.014 for zinc). |
| **d) Effect size** | **NA** – no effect‑size metric (e.g., Cohen’s d, η²) is provided for this specific outcome. |
{'metric': 'Number of families', 'impact_direction': 'Decreased', 'significance': 'Significant', 'p_value': '0.017', 'effect_size': 'NA'}
Extracting information for metric: Numbers of orders
**Metric:** Numbers of orders

| Item | Answer |
|------|--------|
| **a) Impact direction** | NA (the paper does not report a clear increase or decrease in the number of orders attributable to historic mining) |
| **b) Significance** | NA (no statistical test of mining impact on “number of orders” is presented) |
| **c) P‑value** | NA (no p‑value is given for this metric) |
| **d) Effect size** | NA (no effect‑size estimate is reported) |
{'metric': 'Numbers of orders', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Arsenic concentration
**Arsenic concentration (metric)**

| Item | Answer |
|------|--------|
| **a) Impact direction** | **NA** – The paper does not state whether arsenic levels are higher or lower because of historic mining relative to a clear reference condition. |
| **b) Significance** | **non‑significant** – In the MANOVA that included arsenic (along with Cd, Zn, Pb, temperature, pH, DO, conductivity) the overall test was not significant (Wilks’ Λ = 1.32, F₍₂₀,₇₂₎ = 1.32, P = 0.247), and arsenic was not highlighted as a significant predictor in any step‑wise analysis. |
| **c) P‑value** | **NA** – No specific p‑value is reported for arsenic alone; only the overall MANOVA p‑value (0.247) is given, which does not isolate arsenic. |
| **d) Effect size** | **NA** – No effect‑size metric (e.g., η², Cohen’s d, regression coefficient) is provided for arsenic. |
{'metric': 'Arsenic concentration', 'impact_direction': 'NA', 'significance': 'Non-significant', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Cadmium concentration
**Cadmium concentration**

| Item | Answer |
|------|--------|
| **a) Impact direction** | **Increase** – the study reports that cadmium levels are elevated in streams affected by historic mining (e.g., mean ≈ 0.6 mg L⁻¹, and noted as higher than background/reference levels). |
| **b) Significance** | **significant** – cadmium was found to be significantly correlated with reduced insect abundance, families, Plecoptera % and Shannon H (p = 0.017). |
| **c) P‑value** | **0.017** (reported for the cadmium effect in the MANOVA/stepwise analyses). |
| **d) Effect size** | **NA** – the paper does not provide an explicit effect‑size metric (e.g., Cohen’s d, η²) for cadmium. |
{'metric': 'Cadmium concentration', 'impact_direction': 'Increased', 'significance': 'Significant', 'p_value': '0.017', 'effect_size': 'NA'}
Extracting information for metric: Lead concentration
**Lead concentration (metric)**

| Item | Answer |
|------|--------|
| **a) Impact direction** | NA – the paper does not state whether lead levels are higher or lower because of historic mining (the focus is on cadmium and zinc). |
| **b) Significance** | non‑significant – lead was not identified as a significant predictor of insect diversity in the MANOVA/stepwise analyses. |
| **c) P‑value** | NA – no p‑value is reported for a lead‑specific effect. |
| **d) Effect size** | NA – the study does not provide an effect‑size estimate for lead. |
{'metric': 'Lead concentration', 'impact_direction': 'NA', 'significance': 'Non-significant', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Zinc concentration
**Zinc concentration**

| Item | Answer |
|------|--------|
| **a) Impact direction** | **Increased** – the study reports that zinc levels are elevated in streams affected by historic mining (e.g., mean Zn = 167 mg kg⁻¹, higher downstream of mine adits, and positively correlated with reduced insect diversity). |
| **b) Significance** | **Significant** – zinc was found to be significantly correlated with the diversity metrics (MANOVA: F₄,₂₄ = 3.88, P = 0.014). |
| **c) P‑value** | **0.014** (from the MANOVA test linking zinc to the dependent variables). |
| **d) Effect size** | **NA** – the paper does not provide an explicit effect‑size measure (e.g., Cohen’s d, η²) for zinc. |
{'metric': 'Zinc concentration', 'impact_direction': 'Increased', 'significance': 'Significant', 'p_value': '0.014', 'effect_size': 'NA'}
Extracting information for metric: Water temperature
**Water temperature**

| Item | Answer |
|------|--------|
| **a) Impact direction** | NA |
| **b) Significance** | NA |
| **c) P‑value** | NA |
| **d) Effect size** | NA |

*Explanation*: The paper reports the mean water‑temperature of the sampled streams (11.64 ± 0.02 °C) but does not provide a comparison to a reference condition (e.g., pre‑mining or unimpacted streams), nor does it test whether mining has altered temperature. Consequently, no direction of impact, statistical significance, p‑value, or effect‑size is reported for water temperature.
{'metric': 'Water temperature', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Water pH
**Water pH**

| Item | Answer |
|------|--------|
| **a) Impact direction** | NA |
| **b) Significance** | NA |
| **c) P‑value** | NA |
| **d) Effect size** | NA |

*Explanation*: The study measured stream pH (mean = 7.21 ± 0.09) but did not report any comparison of pH between mined‑impact sites and reference sites, nor did it test or quantify a change in pH attributable to historic mining. Consequently, no direction of impact, statistical significance, p‑value, or effect‑size information is provided for this metric.
{'metric': 'Water pH', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Water dissolved oxygen
**Water dissolved oxygen**

| Item | Answer |
|------|--------|
| **a) Impact direction** | NA |
| **b) Significance** | NA |
| **c) P‑value** | NA |
| **d) Effect size** | NA |

*Explanation*: The paper reports the mean dissolved‑oxygen concentration of the sampled streams (10.87 ± 0.14 mg L⁻¹) and notes that the abiotic conditions were “favorable for invertebrate stream taxa.” No quantitative comparison (e.g., before‑ vs. after‑mining or reference vs. impacted sites) is provided for dissolved oxygen, nor are any statistical tests, p‑values, or effect‑size metrics reported for this variable. Consequently, all fields are marked as **NA**.
{'metric': 'Water dissolved oxygen', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}
Extracting information for metric: Water conductivity
**Water Conductivity**

| Item | Answer |
|------|--------|
| **a) Impact direction** | NA |
| **b) Significance** | NA |
| **c) P‑value** | NA |
| **d) Effect size** | NA |

*Explanation*: The paper reports the mean conductivity of the sampled streams (505 ± 41 µS cm⁻¹) but does not provide a comparison to a reference condition, nor does it test or discuss any change in conductivity attributable to historic mining. Consequently, no direction of impact, statistical significance, p‑value, or effect‑size is reported for this metric.
{'metric': 'Water Conductivity', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}

In [182]:
df

,Metric,Metric category,Impact direction,Significance,P value,Effect size
1,Shannon H,Biodiversity metric,Decreased,Significant,0.017,NA
2,Richness J,Biodiversity metric,NA,NA,NA,NA
3,Evenness E,Biodiversity metric,NA,NA,NA,NA
4,Percent of Ephemeroptera,Biodiversity metric,NA,NA,NA,NA
5,Percent of Plecoptera,Biodiversity metric,Decreased,Significant,0.017,NA
6,Percent of Trichoptera,Biodiversity metric,NA,NA,NA,NA
7,Total number of collected animals,Biodiversity metric,Decreased,Significant,Cadmium: 0.017; Zinc: 0.014,NA
8,Number of families,Biodiversity metric,Decreased,Significant,0.017,NA
9,Numbers of orders,Biodiversity metric,NA,NA,NA,NA
10,Arsenic concentration,Environmental metric,NA,Non-significant,NA,NA
11,Cadmium concentration,Environmental metric,Increased,Significant,0.017,NA
12,Lead concentration,Environmental metric,NA,Non-significant,NA,NA
13,Zinc concentration,Environmental metric,Increased,Significant,0.014,NA
14,Water temperature,Environmental metric,NA,NA,NA,NA
15,Water pH,Environmental metric,NA,NA,NA,NA
16,Water dissolved oxygen,Environmental metric,NA,NA,NA,NA
17,Water conductivity,Environmental metric,NA,NA,NA,NA

In [510]:
user_prompt_1 = "Carefully read this mining-impact study:\n\n" + markdown_text + "\n\n" + text_prompt
    
response, messages = functions.extract_information(ollama, MODEL_Lang, SEED, system_prompt, images=False, prompt = user_prompt_1)
print("response", response)

response **1. Scale**
- **Answer:** **Regional**
- **Reasoning:** The study is confined to the Idaho Panhandle National Forests (IPNF) in northern Idaho, covering 10 streams within a ~5 km² area. This is a sub‑national (regional) assessment rather than a single‑site case study or a worldwide analysis.

---

**2. Country / Continent**
- **Answer:** United States (North America)

---

**3. Specific location**
- **Answer:** Northern Idaho, USA – Idaho Panhandle National Forests, Mt. Coeur d’Alene area; streams that are tributaries to the lower South Fork of the Coeur d’Alene River.

---

**4. Mined commodities**
- **Answer:**
  1. **Silver** (the historic “silver (galena) mining” mentioned)
  2. **Lead** (galena is a lead‑sulfide ore, often mined for its lead content)

*The paper also discusses the presence of cadmium, zinc and arsenic in the waste, but these are treated as contaminants rather than the primary mined commodities.*

---

**5. Mining stage**
- **Answer:** **Closed** (abandoned) – mining activity ceased at least by 1910–1932 and no current operations are reported.

---

**6. Type of mining activity**
- **Answer:** **Underground** (presence of “mine adits”) and **artisanal small‑scale mining** (the study emphasizes “one‑ and two‑man operations”).
- **If a strict classification is required:** *Underground* is the most directly supported term; other categories (open‑cut, placer, etc.) are not mentioned → **NA** for those.

---

**7. Experimental design**
- **Answer:** **Pre‑mining vs post‑mining**
- **Reasoning:** The authors compare present‑day insect communities (post‑mining) with the historic baseline (pre‑mining) inferred from the fact that mining stopped > 70 years ago. They do not have a contemporaneous “non‑mining” control; instead they assess how legacy contamination has altered the community relative to the presumed pre‑disturbance condition.

---

**8. Taxonomic groups**
- **Answer:** **Aquatic insects (benthic macroinvertebrates)** – specifically larval orders *Ephemeroptera* (mayflies), *Plecoptera* (stoneflies) and *Trichoptera* (caddisflies).

---

**9. Biomes of assessment**
- **Answer:** **Freshwater** (lotic stream habitats).

---

**10. Method of assessment**
- **Answer:**
  - **In‑situ sampling** (Surber sampler for insects; sediment grabs for metals)
  - **Laboratory analysis** (ICP‑OES metal quantification; ethanol preservation and taxonomic identification)
  - **Statistical analysis** (linear regression, MANOVA, stepwise MANOVA)

---

**11. Specific methodology**

| Step | What was done | Details |
|------|---------------|---------|
| **Insect collection** | Surber sampler (500 µm mesh) in riffle sections | 6 samples per site (3 in main flow, 3 near shore); rocks 5–10 cm (or up to 50 cm) were rinsed; substrate stirred for 2 min; organisms transferred to 95 % ethanol (final concentration < 95 % due to rain). |
| **Identification** | Sorted to genus level in the lab | Preserved specimens examined under microscope; counts per order (Ephemeroptera, Plecoptera, Trichoptera) and total individuals recorded. |
| **Sediment collection** | 100 cc sediment from each riffle | Dried 48 h at 58 °C, sieved through 63 µm screen, stored in acid‑washed polypropylene jars. |
| **Metal analysis** | ICP‑OES (Inductively Coupled Plasma Optical Emission Spectrometry) | Samples digested using EPA SW846 method 3050, analyzed per EPA method 6010B at SVL Analytical (Kellogg, ID). Metals measured: As, Cd, Pb, Zn (also Cu, Mn, Hg, Ni reported as below relevance). |
| **Abiotic water variables** | Measured in‑field | pH, temperature, dissolved O₂, conductivity (mean ± SE reported). |
| **Statistical approach** | • Linear regression to test correlation between bulk soil metal levels and insect counts (R² = 0.939). <br>• MANOVA on all dependent (metal + water) vs independent (diversity indices, % orders, total animals, families, orders). <br>• Stepwise MANOVA identified Cd & Zn as significant predictors of lower animal numbers, families, % Plecoptera, and Shannon H (P ≈ 0.014–0.017). |
| **Diversity metrics** | Shannon H, Shannon J, Shannon E, richness, evenness | Calculated using standard formulas (pᵢ = proportion of species i). |

---

**12. Temporal scale**
- **Answer:** **50‑100 years**
- **Reasoning:** Mining ceased “at least 75 years” ago (no activity since 1910–1932). The study was conducted in 2005, so the elapsed time is roughly 70–95 years, fitting the 50‑100 year bracket.

---

**13. Type of impact or pressure**
- **Answer:** **Observed impact** – the study documents statistically significant reductions in insect abundance, family richness, and diversity indices that are directly linked to measured heavy‑metal concentrations.

---

**14. Impact pathway**
- **Answer:** **Ecotoxicity** – heavy‑metal contamination of stream sediments (Cd, Zn, As, Pb) leads to toxic effects on benthic macroinvertebrates. No explicit mention of acidification, water depletion, land‑use change, climate change, or eutrophication.

---

**15. Description of impact or pressure**

- **Key finding:** “*cadmium and zinc levels were significantly correlated with fewer animals, fewer families, a smaller percentage of plecopterans, and lower Shannon H diversity values*.” (Results section)
- **Supporting quote:** “*Stepwise MANOVAs indicated high positive correlation between cadmium and zinc with the number of animals, the number of families, the percent of animals made up of plecopterans, and Shannon H*” (Results).
- **Interpretation:** Legacy metal leaching from abandoned mines continues to exert toxic pressure on stream insect communities, especially on the sensitive order Plecoptera, resulting in measurable declines in community diversity even after > 70 years of mining cessation.

---

**16. Spatial scale**
- **Answer:** **NA**
- **Reasoning:** The manuscript states that all streams lie within a ~5 km² area and that three mine adits were located, with upstream/downstream comparisons shown in Figure 5. However, it does **not** give explicit distances (e.g., “X km downstream of the adit”) between the mining source and the sampling points. Therefore a quantitative distance range cannot be assigned.

---

*All sections include the reasoning behind the chosen answer and cite the relevant portions of the paper where the information is found.*

In [514]:
user_prompt_2 = "Carefully read this mining-impact study:\n\n" + markdown_text + "\n\nTables from the text: " + text_tables + "\n\n" + text_prompt_diversity_metrics
    
response_metrics, messages_metrics = functions.extract_information(ollama, MODEL_Lang, SEED, system_prompt, images=False, image_paths=image_paths, prompt = user_prompt_2)
print("response_metrics", response_metrics)

response_metrics **A.  Metrics that were actually measured, modelled or otherwise estimated in the paper**

| # | Metric (as written in the article) |
|---|------------------------------------|
| 1 | Shannon **H** diversity index |
| 2 | Shannon **J** (Pielou’s evenness) |
| 3 | Shannon **E** (evenness) |
| 4 | **Richness** value (species‑richness) |
| 5 | **Evenness** value |
| 6 | % **Ephemeroptera** (percent of total organisms) |
| 7 | % **Plecoptera** (percent of total organisms) |
| 8 | % **Trichoptera** (percent of total organisms) |
| 9 | **Total number of collected animals** (abundance) |
|10 | **Number of families** (taxonomic richness at family level) |
|11 | **Number of orders** (taxonomic richness at order level) |
|12 | **Arsenic** concentration in stream sediments (mg kg⁻¹) |
|13 | **Cadmium** concentration in stream sediments (mg kg⁻¹) |
|14 | **Lead** concentration in stream sediments (mg kg⁻¹) |
|15 | **Zinc** concentration in stream sediments (mg kg⁻¹) |
|16 | **Water temperature** (°C) |
|17 | **Water pH** |
|18 | **Dissolved oxygen** (mg L⁻¹) |
|19 | **Conductivity** (µS cm⁻¹) |

*No physiological, molecular or cellular measurements on individual organisms were reported, so no sub‑organismal metrics are present.*

---

**B.  Grouping of the extracted metrics**

| Category | Metrics placed in the category | Reasoning |
|----------|--------------------------------|-----------|
| **Biodiversity metric** | 1‑11 (Shannon H, J, E; richness; evenness; % Ephemeroptera, % Plecoptera, % Trichoptera; total abundance; number of families; number of orders) | All of these describe the composition, richness, evenness or abundance of taxa at the **species‑/community‑level**. They are explicitly used to assess how the insect community varies with mining impact. |
| **(Sub)-organismal metric** | *None* | The study never measured traits of individual organisms (e.g., enzyme activity, gene expression, growth rate). |
| **Environmental metric** | 12‑19 (Arsenic, Cadmium, Lead, Zinc, water temperature, pH, dissolved O₂, conductivity) | These quantify the **abiotic** conditions of the streams or sediments. They are not measures of biodiversity or organismal physiology, but of water‑quality/contaminant levels that may drive ecological effects. |

---

**C.  Impact direction, statistical significance, p‑value and effect size for each metric**

| # | Metric | Direction of change **due to historic mining** (relative to an assumed un‑impacted reference) | Significance reported? | p‑value (if given) | Effect size (if given) |
|---|--------|------------------------------------------------------------|------------------------|--------------------|------------------------|
| 1 | Shannon H diversity index | **Decreased** – streams with higher Cd & Zn had lower Shannon H values. | Yes (significant) | 0.017 (step‑wise MANOVA) | – (no explicit effect‑size reported) |
| 2 | Shannon J (evenness) | Not explicitly reported (no statement of change). | **NA** | NA | NA |
| 3 | Shannon E (evenness) | Not explicitly reported. | **NA** | NA | NA |
| 4 | Richness value (species richness) | Not directly reported; only “number of families” is discussed. | **NA** | NA | NA |
| 5 | Evenness value | Not directly reported. | **NA** | NA | NA |
| 6 | % Ephemeroptera | **No detectable change** – authors state Ephemeroptera were *not* impacted. | Non‑significant (authors say “were not impacted”) | NA | NA |
| 7 | % Plecoptera | **Decreased** – lower % Plecoptera with higher Cd & Zn. | Yes (significant) | 0.017 (step‑wise MANOVA) | – |
| 8 | % Trichoptera | Not explicitly reported as changed. | **NA** | NA | NA |
| 9 | Total number of collected animals | **Decreased** – fewer animals where Cd & Zn were higher. | Yes (significant) | 0.017 (step‑wise MANOVA) | – |
|10 | Number of families | **Decreased** – fewer families with higher Cd & Zn. | Yes (significant) | 0.017 (step‑wise MANOVA) | – |
|11 | Number of orders | Not reported as changed. | **NA** | NA | NA |
|12 | Arsenic (sediment) | **Increased** – mining legacy leaves detectable As; however the paper does not test a reference, so statistical significance is not reported. | **NA** | NA | NA |
|13 | Cadmium (sediment) | **Increased** – higher Cd concentrations are linked to reduced biodiversity. No direct test vs. reference, so significance not reported. | **NA** | NA | NA |
|14 | Lead (sediment) | **Increased** – measured but not linked to biodiversity changes; no significance test reported. | **NA** | NA | NA |
|15 | Zinc (sediment) | **Increased** – higher Zn associated with lower biodiversity. No direct reference test. | **NA** | NA | NA |
|16 | Water temperature | No systematic difference reported; streams “appeared pristine”. | Non‑significant / not tested | NA | NA |
|17 | Water pH | No systematic difference reported; neutral pH across sites. | Non‑significant / not tested | NA | NA |
|18 | Dissolved oxygen | No systematic difference reported; well‑oxygenated streams. | Non‑significant / not tested | NA | NA |
|19 | Conductivity | No systematic difference reported; values within a narrow range. | Non‑significant / not tested | NA | NA |

**Notes on interpretation**

* The paper’s primary statistical finding is the **step‑wise MANOVA** that linked **cadmium and zinc** to four biodiversity response variables (total animals, families, % Plecoptera, Shannon H). The reported Wilks’ Λ test gave **p = 0.017**, which we have applied to each of those four response metrics (items 1, 7, 9, 10).

* For metrics where the authors explicitly state “were not impacted” (e.g., Ephemeroptera) we record the direction as “no detectable change” and note the result as **non‑significant** (even though a p‑value is not given).

* Environmental concentrations (As, Cd, Pb, Zn, temperature, pH, O₂, conductivity) are reported as raw measurements; the manuscript does not provide a statistical comparison to a pristine baseline, so we list the direction as “increased” (because mining is the source of the metals) but mark significance as **NA**.

* No sub‑organismal (physiological, molecular, cellular) metrics were measured, so that category remains empty.

---

**Summary**

The study relied on a suite of **biodiversity metrics** (diversity indices, taxonomic counts, and community composition percentages) to detect the lingering ecological imprint of historic mining. The only **environmental metrics** that showed a clear link to those biodiversity declines were **cadmium and zinc** concentrations in stream sediments. All other measured abiotic variables (temperature, pH, dissolved oxygen, conductivity, arsenic, lead) were reported as within normal ranges and not statistically linked to the observed biotic changes. No organism‑level physiological measurements were taken.

In [512]:
json_response = functions.get_json_table(ollama, MODEL_Lang, SEED, system_prompt, user_prompt_1, response, prompt_format)
print(json_response)

{'scale': 'Regional', 'country_or_continent': 'United States (North America)', 'specific_location': "Northern Idaho, Idaho Panhandle National Forests (Mt. Coeur d'Alene area, tributary streams to the South Fork of the Coeur d'Alene River)", 'mined_commodities': 'Silver (galena), Lead, Zinc', 'mining_stage': ['Closed'], 'type_of_mining_activity': ['NA'], 'experimental_design': ['NA'], 'taxonomic_groups': 'Aquatic macroinvertebrate insects (larval stream insects – Ephemeroptera, Plecoptera, Trichoptera)', 'biomes_of_assessment': ['Freshwater'], 'method_of_assessment': ['In-situ sampling', 'Laboratory analysis', 'Statistical analysis'], 'specific_methodology': 'Surber sampler (500‑µm mesh) was used to collect benthic insects from riffle habitats at three sites per stream (30 sites total). Samples were preserved in ethanol, sorted to genus, and counted. Sediment (100\u202fcc) from each riffle was collected, dried, digested (EPA SW846 method 3050) and analyzed for As, Cd, Pb, Zn by ICP‑OES (EPA method 6010B). Metal concentrations were correlated with insect community metrics (total abundance, families, % Plecoptera, Shannon H) using linear regression and MANOVA (stepwise) in JMP (SAS).', 'temporal_scale': '50-100', 'type_of_impact_or_pressure': 'Observed impact', 'impact_pathway': ['Ecotoxicity'], 'description_of_impact_or_pressure': 'The study reports that “cadmium and zinc levels were significantly correlated with fewer animals, fewer families, a smaller percentage of plecopterans, and lower Shannon H diversity values.” It also notes “after at least 75 years, abandoned mines appear to be still influencing stream communities.”', 'spatial_scale': 'NA'}

In [515]:
json_response_metrics = functions.get_json_table(ollama, MODEL_Lang, SEED, system_prompt, user_prompt_2, response_metrics, prompt_format_metrics)
print(json_response_metrics)

[{'metric': 'Shannon H', 'metric_category': 'Biodiversity metric', 'impact_direction': 'Decreased', 'significance': 'Significant', 'p_value': '.017 (cadmium) / .014 (zinc)', 'effect_size': 'NA'}, {'metric': 'Shannon J', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Shannon E', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': '% Ephemeroptera', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': '% Plecoptera', 'metric_category': 'Biodiversity metric', 'impact_direction': 'Decreased', 'significance': 'Significant', 'p_value': '.017 (cadmium) / .014 (zinc)', 'effect_size': 'NA'}, {'metric': '% Trichoptera', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Total number of collected animals', 'metric_category': 'Biodiversity metric', 'impact_direction': 'Decreased', 'significance': 'Significant', 'p_value': '.017 (cadmium) / .014 (zinc)', 'effect_size': 'NA'}, {'metric': 'Number of families', 'metric_category': 'Biodiversity metric', 'impact_direction': 'Decreased', 'significance': 'Significant', 'p_value': '.017 (cadmium) / .014 (zinc)', 'effect_size': 'NA'}, {'metric': 'Number of orders', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Arsenic (mg/kg)', 'metric_category': 'Environmental metric', 'impact_direction': 'Increased', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Cadmium (mg/kg)', 'metric_category': 'Environmental metric', 'impact_direction': 'Increased', 'significance': 'Significant', 'p_value': '0.017', 'effect_size': 'NA'}, {'metric': 'Lead (mg/kg)', 'metric_category': 'Environmental metric', 'impact_direction': 'Increased', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Zinc (mg/kg)', 'metric_category': 'Environmental metric', 'impact_direction': 'Increased', 'significance': 'Significant', 'p_value': '0.014', 'effect_size': 'NA'}, {'metric': 'pH', 'metric_category': 'Environmental metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Water temperature (°C)', 'metric_category': 'Environmental metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Dissolved oxygen (mg/L)', 'metric_category': 'Environmental metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Conductivity (µS/cm)', 'metric_category': 'Environmental metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Abundance of Ephemeroptera (raw count)', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Abundance of Plecoptera (raw count)', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Abundance of Trichoptera (raw count)', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Abundance of Coleoptera (raw count)', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}, {'metric': 'Abundance of Diptera (raw count)', 'metric_category': 'Biodiversity metric', 'impact_direction': 'NA', 'significance': 'NA', 'p_value': 'NA', 'effect_size': 'NA'}]

In [446]:
import importlib
import functions
importlib.reload(functions)

# testing... 

study_id = "2758"

# ----------------------------------------------------------------
# Excel setup

all_cols = ["Scale", "Country/Continent", "Specific location", "Mined commodities", "Mining stage", "Type of mining activity", "Experimental design",
"Taxonomic groups", "Biomes of assessment","Method of assessment","Specific methodology", "Temporal scale", "Type of impact or pressure", 
"Impact pathway", "Description of impact or pressure", "Spatial scale", "Metric", "Metric category", "Impact direction", "Significance", 
"P-value", "Response study", "Response metrics", "Extracted tables", "Study ID"]

output_file = Path(f"output-train_{study_id}.xlsx")
if output_file.exists():
    wb = load_workbook(output_file)
    ws = wb.active
else:
    wb = Workbook()
    ws = wb.active
    ws.append(list(all_cols))
    wb.save(output_file)

# extraction... 
start_time = time.time()

image_paths = pdf_to_images(study_id)

extracted_text = ""
with pdfplumber.open(f"training_set/{study_id}.pdf") as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        if text:  # avoid None for empty pages
            extracted_text += text + "\n\n"  # add spacing between pages

# 1. extract tables from the text, to ensure correct interpretation of results 
print("Extracting tables from the text...")
text_tables, _ = functions.extract_tables(ollama, MODEL, SEED, system_prompt, extracted_text, image_paths) 

# 2. get names of individual mines, if assessed individually in the study: 
print("Determining whether multiple mines are assessed individually in the study...") 
mines, _ = functions.get_mines(ollama, MODEL, SEED, system_prompt, json_format_mines, image_paths) 

if (mines is None) or (mines=={}) or (mines.get("Mine names", [])==[]): 
    print("No individual mines found, starting extraction for complete study...")
    
    df = functions.get_full_response_json(ollama, MODEL, SEED, study_id, system_prompt, text_prompt, text_prompt_diversity_metrics, 
                                    text_tables, prompt_format, prompt_format_metrics, image_paths, extracted_text
                                   )

    df = df[all_cols] # reorder columns 

    # append to excel workbook 
    for j, row in enumerate(df.itertuples(index=False), start=1):
        ws.append(row)
        
    print("Done.")
    
else: 
    print(f"Multiple mines found: {', '.join(mines.get("Mine names"))}")

    for mine in mines.get("Mine names"):
        print(f"Starting extraction for mine: {mine}...")
        
        df = functions.get_full_response_json(ollama, MODEL, SEED, study_id, system_prompt, text_prompt_mine.format(mine=mine), text_prompt_diversity_metrics, 
                                              text_tables, prompt_format, prompt_format_metrics, image_paths, extracted_text,
                                              prompt_prefix = f"For the mine named '{mine}' specifically, do the following:"
                                             )

        df['Scale'] = "Local" # per definition 
        df = df[all_cols] # reorder columns 

        df["P-value"] = (
            df["P-value"]
            .astype(str)
            .apply(lambda x: re.sub(r"^/(\d)", r"\1", x.strip()))  # remove leading "/" before digits
        )

        # append to excel workbook 
        for j, row in enumerate(df.itertuples(index=False), start=1):
            ws.append(row)
            
        print("Done.")

wb.save(output_file)

elapsed = time.time() - start_time
print(f"Finished in {elapsed/60:.2f} minutes")

KeyboardInterrupt:

In [444]:
# 1. extract tables from the text, to ensure correct interpretation of results 
print("Extracting tables from the text...")
text_tables, _ = functions.extract_tables(ollama, MODEL, SEED, system_prompt, extracted_text, image_paths)

Extracting tables from the text...

In [445]:
text_tables

"Table 1\n\nWater quality parameters of the Zalya-Elila River (stretching along Mwenga territory).\n\n| Water parameters | Sites surveyed | Average | P-value | Acceptable levels* |\n|------------------|----------------|---------|--------|--------------------|\n|                  | Site A         | Site B  | Site C |                    |\n| Temperature (°C) | 24.45±0.05     | 24.35±0.25 | 24.50±0.10 | 24.43±0.13 | 0.805 | 20–25°C |\n| pH               | 6.25±0.45      | 6.4±0.03  | 5.90±0.20 | 6.18±0.23 | 0.521 | 6.5–8.5 |\n| EC (μS/cm)       | 300.00±90.00b  | 490.00±120.00ab | 845.00±25.00a | 545.00±78.33 | 0.048* | 500–1000 |\n| TDS (mg/L)       | 140.00±40.00b  | 235.00±55.00ab | 410.00±10.00a | 261.67±35.00 | 0.037* | 500–1500 |\n| DO (mg/L)        | 5.21±0.71      | 4.90±0.51 | 7.55±0.20 | 5.89±0.47 | 0.064 | >5.00 |\n| BOD5 (mg/L)      | 3.88±0.82      | 2.81±0.05 | 2.40±0.97 | 3.03±0.61 | 0.441 | <5.00 |\n| COD (mg/L)       | 6.55±4.95      | 6.70±4.50 | 2.45±0.35 | 5.23±3.27 | 0.707 | <5.00 |\n| Magnesium (mg/L) | 31.00±1.00     | 35.00±8.00 | 73.00±18.00 | 46.00±9.00 | 0.137 | 10–25 |\n| Chlorite (mg/L)   | 17.73±1.42     | 21.63±0.35 | 16.31±1.42 | 18.55±1.06 | 0.100 | <50 |\n| Sulfate (mg/L)    | 102.732±2.88   | 99.84±1.92 | 111.36±8.64 | 104.64±4.48 | 0.404 | <250 |\n| Nitrate (mg/L)    | 0.53±0.01      | 0.60±0.05 | 0.55±0.02 | 0.56±0.03 | 0.359 | <50 |\n\n*Water parameter acceptable levels in natural water bodies for aquatic animals (ANZECC, ARMCANZ, 2000; WHO, 2017).\n\n---\n\nTable 2\n\nCharacteristics of the generated fisher's classes.\n\n| Characteristic variables | Characteristics of classes | Average±Std/ Frequency | P-value |\n|-------------------------|---------------------------|------------------------|---------|\n| Modalities              | 1                         | 2                      |         |\n| Age (years)             | 38.08±11.09b             | 51.35±8.69a            | 43.04±12.08 | 0.003** |\n| Household size (number) | 7.21±2.82                 | 6.94±2.79              | 7.11±2.8   | 0.061   |\n| Monthly income (USD)    | 108.67±66.34b            | 150.03±62.97a          | 124.12±67.77 | 0.008** |\n| Experience (years)      | 20.94±11.68a             | 19.55±10.15b           | 20.42±11.09 | 0.049*  |\n| Species (15 years ago)  | 6.92±0.33                 | 6.90±0.40              | 6.92±0.36  | 0.090   |\n| Species (Current)       | 4.94±0.24                 | 4.97±0.18              | 4.95±0.22  | 0.100   |\n| Mining sites (number)   | 1.63±0.60b                | 3.29±0.97a             | 2.25±1.10  | 2.00E-10*** |\n| Distance (Stream-Site)  | 22.4±79.90a               | 13.42±38.18b           | 19.05±67.26 | 0.008** |\n| Fishing hours per day   | 5.77±3.19a                | 3.68±2.02b             | 4.99±2.98  | 0.004** |\n| Weekly fishing frequency| 3.75±1.01b                | 5.58±1.18a             | 4.43±1.39  | 1.00E-10*** |\n| Current quantity (Kg)   | 3.62±3.39b                | 4.45±1.88a             | 3.93±2.93  | 4.00E-09*** |\n| Quantity (in Kg 15 years ago) | 6.96±3.11b | 9.00±4.20a | 7.72±3.67 | 2.00E-09*** |\n| Gender                  | Female                    | 17.31%                 | 32.26%     | 25.44%  | 0.117   |\n|                         | Male                      | 82.69%                 | 67.74%     | 74.56%  |        |\n| Marital statutes        | Single                    | 11.54%                 | 16.13%     | 14.04%  | 0.551   |\n|                         | Divorced                  | 0.00%                  | 3.23%      | 1.75%   |        |\n|                         | Married                   | 75.00%                 | 70.97%     | 72.81%  |        |\n|                         | Widower                   | 13.46%                 | 9.68%      | 11.40%  |        |\n| Level education         | No level                  | 34.62%                 | 22.58%     | 28.07%  | 0.248   |\n|                         | Primary                   | 38.46%                 | 32.26%     | 35.09%  |        |\n|                         | Secondary                 | 25.00%                 | 38.71%     | 32.46%  |        |\n|                         | Higher                    | 1.92%                  | 6.45%      | 4.39%   |        |\n| Main activity           | Fishing                   | 21.15%                 | 3.23%      | 11.40%  | 0.040*  |\n|                         | Fish farming              | 78.85%                 | 96.77%     | 88.60%  |        |\n| Secondary activity      | No                        | 53.85%                 | 38.71%     | 45.61%  | 0.004** |\n|                         | Yes                       | 46.15%                 | 61.29%     | 54.39%  |        |\n\nStd: Standard deviation\n\n---\n\nTable 3\n\nMining sites and fishing techniques.\n\n| Variables | Modalities | Characteristics of classes | General total | Pearson Test |\n|-----------|------------|----------------------------|---------------|--------------|\n|           |            | 1                          | 2             | Chi-square   | P-value |\n| Mining site (Upstream) | No         | 25.00%                     | 22.58%        | 23.68%       | 0.01    | 0.910 |\n|           | Yes        | 75.00%                     | 77.42%        | 76.32%       |         |       |\n| Sediments in water | No         | 1.92%                      | 6.45%         | 4.39%        | 1.14    | 0.285 |\n|           | Yes        | 98.08%                     | 93.55%        | 95.61%       |         |       |\n| Mortalities | No         | 36.54%                     | 9.68%         | 21.93%       | 6.00    | 0.020 |\n|           | Yes        | 63.46%                     | 90.32%        | 78.07%       |         |       |\n| Fishing equipment | Hooks      | 32.69%                     | 35.48%        | 34.21%       | 8.00    | 0.044 |\n|           | Nets       | 28.85%                     | 19.35%        | 23.68%       |         |       |\n|           | Spears     | 11.54%                     | 0.00%         | 5.26%        |         |       |\n|           | Traps      | 26.92%                     | 45.16%        | 36.84%       |         |       |\n| Fishing methods | Direct fishing | 67.31% | 67.74% | 67.54% | 0.04 | 0.900 |\n|           | Trapping   | 32.69%                     | 32.26%        | 32.46%       |         |       |\n| Fishing time | Day        | 38.46%                     | 25.81%        | 33.73%       |         |       |\n|           | Night      | 0.00%                      | 22.58%        | 8.43%        | 13.0    | 0.001 |\n|           | Day and night | 61.54% | 51.61% | 57.83% |       |       |\n\n---\n\nTable 4\n\nFisher’s perception of the impact of mining on fish yield and diversity, water quality and human health.\n\n| Variables | Modalities | Characteristic of classes | Average | Pearson Test |\n|-----------|------------|---------------------------|---------|--------------|\n|           |            | Class 1                   | Class 2 | Chi-square   | P-value |\n| Effects of mining activities on fish diversity | No | 57.69% | 66.67% | 60.98% | 0.3 | 0.6 |\n|           | Yes        | 42.31%                    | 33.33%  | 39.02%       |         |     |\n| Trend of fish captures (15 years ago to date) | Decrease | 94.23% | 93.55% | 93.98% | 0.02 | 0.9 |\n|           | No change  | 5.77%                     | 6.45%   | 6.02%        |         |     |\n| Captured fish size (Current status) | Large | 15.38% | 19.35% | 16.87% | 9.91 | 0.007 |\n|           | Medium     | 46.15%                    | 12.90%  | 33.73%       |         |     |\n|           | Small      | 38.46%                    | 67.74%  | 49.40%       |         |     |\n| Captured fish size (15 years ago) | Large | 71.15% | 12.90% | 49.40% | 41.19 | 1.13E-09 |\n|           | Medium     | 15.38%                    | 87.10%  | 42.17%       |         |     |\n|           | Small      | 13.46%                    | 0.00%   | 8.43%        |         |     |\n| Effect of mining activities on water quality | Not significant | 17.31% | 16.13% | 16.67% | 0.002 | 0.9 |\n|           | Significant | 82.69%                    | 83.87%  | 83.33%       |         |     |\n| Type of effect on water quality | None | 11.54% | 12.90% | 12.28% | 0.639 | 0.727 |\n|           | Color change | 63.46% | 54.84% | 58.77% |       |       |\n|           | Turbidity  | 25.00%                    | 32.26%  | 28.95%       |         |     |\n| Effects of pollutants on fish fertility | No | 1.92% | 3.23% | 2.63% | 0.002 | 0.9 |\n|           | Yes        | 98.08%                    | 96.77%  | 97.37%       |         |     |\n| Observation of high fish mortality | No | 30.77% | 19.35% | 24.56% | 0.8 | 0.4 |\n|           | Yes        | 69.23%                    | 80.65%  | 75.44%       |         |     |\n| Causes of mass mortality | Unknown | 30.77% | 19.35% | 24.56% | 10.02 | 0.03 |\n|           | Mining residues | 40.38% | 67.74% | 55.26% |       |       |\n|           | Diseases   | 23.08%                    | 12.90%  | 17.54%       |         |     |\n|           | Overpopulation | 5.77% | 0.00% | 2.63% |       |       |\n| Effects on human health | No | 84.62% | 87.10% | 85.96% | 0.009 | 0.901 |\n|           | Yes        | 15.38%                    | 12.90%  | 14.04%       |         |     |\n| Type of effects on human health | Allergy | 11.54% | 3.23% | 7.02% | 2.00 | 0.401 |\n|           | No         | 86.69%                    | 87.10%  | 85.09%       |         |     |\n|           | Breathing difficulties | 5.77% | 9.68% | 7.89% |       |       |\n\n---\n\nTable 5\n\nFactors determining the perception of fishers towards the effect of mining on fish diversity.\n\n| Independent variables | Modalities | Effect on fish diversity | Coefficient | OR | IC 95% | P-value |\n|-----------------------|------------|-------------------------|-------------|----|-------|---------|\n|                       |            | No                      | Yes         |    | IC-   | IC+     |\n| Classes               | 1          | 57.69%                  | 42.31%      | -  | -     | -       | -   |\n|                       | 2          | 64.52%                  | 35.48%      | -0.28 | 0.75  | 0.29    | 1.90 | 0.039* |\n| Areas                 | Basile     | 83.33%                  | 16.67%      | -  | -     | -       | -   |\n|                       | Wamuzimu   | 57.80%                  | 42.20%      | 0.93 | 3.56  | 0.56    | 6.99 | 0.030* |\n| Age                   | 19–25 years| 100.00%                 | 0.00%       | -  | -     | -       | -   |\n|                       | 26–35 years| 52.63%                  | 47.37%      | 20.14 | Inf.  | -       | Inf. | 0.000*** |\n|                       | 35–45 years| 52.63%                  | 47.37%      | 20.14 | Inf.  | -       | Inf. | 0.000*** |\n|                       | >45 years  | 63.41%                  | 36.59%      | 15.18 | Inf.  | -       | Inf. | 0.040* |\n| Gender                | Female     | 47.37%                  | 52.63%      | -  | -     | -       | -   |\n|                       | Male       | 64.06%                  | 35.94%      | -0.65 | 0.52  | 0.14    | 1.84 | 0.034* |\n| Marital status        | Single     | 81.82%                  | 18.18%      | -  | -     | -       | -   |\n|                       | Divorced   | 0.00%                   | 100.00%     | 17.07 | Inf.  | -       | Inf. | 0.000*** |\n|                       | Married    | 59.02%                  | 40.98%      | 1.14 | 3.12  | 0.62    | 5.71 | 0.100 |\n|                       | Widower    | 50.00%                  | 50.00%      | 1.50 | 4.50  | 0.62    | 3.22 | 0.100 |\n| Level of education    | Illiterate | 72.00%                  | 28.00%      | -  | -     | -       | -   |\n|                       | Primary    | 50.00%                  | 50.00%      | 0.94 | 2.57  | 0.83    | 7.95 | 0.027 |\n|                       | Secondary  | 60.00%                  | 40.00%      | 0.53 | 1.71  | 0.52    | 5.60 | 0.041 |\n|                       | University | 66.67%                  | 33.33%      | 0.25 | 1.28  | 0.10    | 3.65 | 0.094 |\n| Household size        | 1 a` 5     | 59.26%                  | 40.74%      | -  | -     | -       | -   |\n|                       | 6 a` 10    | 60.87%                  | 39.13%      | 0.06 | 1.06  | 0.40    | 2.81 | 0.894 |\n|                       | >10        | 60.00%                  | 40.00%      | 0.03 | 1.03  | 0.23    | 2.54 | 0.907 |\n| Main activity         | Fishing    | 50.00%                  | 50.00%      | -  | -     | -       | -   |\n|                       | Fish farming | 61.97% | 38.03% | -0.48 | 0.61 | 0.17 | 2.09 | 0.072 |\n| Experience            | 5–10       | 53.85%                  | 46.15%      | -  | -     | -       | -   |\n|                       | 10–15      | 50.00%                  | 50.00%      | 0.15 | 1.16  | 0.20    | 6.80 | 0.100 |\n|                       | 15–20      | 56.25%                  | 43.75%      | -0.09 | 0.90 | 0.24    | 3.31 | 0.101 |\n|                       | >20        | 70.00%                  | 30.00%      | -0.69 | 0.50 | 0.13    | 1.91 | 0.047 |\n| Species (15 years ago)| <5 fishes  | 60.49%                  | 39.51%      | -  | -     | -       | -   |\n|                       | >5 fishes  | 50.00%                  | 50.00%      | 0.25 | 1.28  | 0.13    | 4.31 | 0.002** |\n| Species (Current)     | <5 fishes  | 60.76%                  | 39.24%      | -  | -     | -       | -   |\n|                       | >5 fishes  | 50.00%                  | 50.00%      | 0.37 | 1.44  | 0.28    | 4.79 | 0.002** |\n| Distance (Stream-Site)| <1km       | 55.56%                  | 44.44%      | -  | -     | -       | -   |\n|                       | 1–5km      | 51.22%                  | 48.78%      | -0.57 | 0.56 | 0.19    | 1.61 | 0.281 |\n|                       | 5–10km     | 65.22%                  | 34.78%      | -0.17 | 0.84 | 0.19    | 3.58 | 0.813 |\n|                       | >10km      | 90.00%                  | 10.00%      | -2.14 | 0.11 | 0.01    | 1.01 | 0.049* |\n| Mining sites          | 1–2sites   | 61.90%                  | 38.10%      | -  | -     | -       | -   |\n|                       | 3–5sites   | 59.68%                  | 40.32%      | 0.09 | 1.09 | 0.39    | 3.03 | 0.044* |\n| Fishing hours per day | 1–3hours   | 71.43%                  | 28.57%      | -  | -     | -       | -   |\n|                       | 3–5hours   | 57.14%                  | 42.86%      | 0.63 | 1.87 | 0.45    | 7.76 | 0.038* |\n|                       | 5–10hours  | 56.10%                  | 43.90%      | 0.67 | 1.96 | 0.63    | 6.06 | 0.024* |\n|                       | >10hours   | 57.14%                  | 42.86%      | 0.63 | 1.87 | 0.32    | 9.02 | 0.048* |\n| Fishing frequency week| 1–3times   | 60.00%                  | 40.00%      | -  | -     | -       | -   |\n|                       | 3–5times   | 62.86%                  | 37.14%      | -0.12 | 0.88 | 0.28    | 2.79 | 0.138 |\n|                       | >5 times   | 57.14%                  | 42.86%      | 0.11 | 1.12 | 0.35    | 3.68 | 0.147 |\n| Quantity (Current)    | 1–5kg      | 58.33%                  | 41.67%      | -  | -     | -       | -   |\n|                       | 6–10kg     | 67.86%                  | 32.14%      | -0.47 | 0.62 | 0.20    | 1.79 | 0.087 |\n|                       | >10kg      | 42.86%                  | 57.14%      | 0.57 | 1.77 | 0.28    | 2.18 | 0.081 |\n| Quantity (15 years ago)| 1–5kg | 55.56% | 44.44% | - | - | - | - |\n|                       | 6–10kg     | 68.57%                  | 31.43%      | -0.37 | 0.73 | 0.19    | 2.84 | 0.202 |\n|                       | >10kg      | 52.38%                  | 47.62%      | 0.30 | 1.35 | 0.33    | 5.76 | 0.204 |\n| Mine site upstream    | No         | 90.00%                  | 10.00%      | -  | -     | -       | -   |\n|                       | Yes        | 50.79%                  | 49.21%      | 1.09 | 2.97 | 0.40    | 6.13 | 0.007** |\n| Sediments in water    | No         | 61.25%                  | 38.75%      | -  | -     | -       | -   |\n|                       | Yes        | 33.33%                  | 66.67%      | 1.15 | 3.15 | 1.31    | 7.43 | 0.000*** |\n| Mortalities           | No         | 50.00%                  | 50.00%      | -  | -     | -       | -   |\n|                       | Yes        | 63.93%                  | 36.07%      | 0.01 | 1.01 | 0.00    | 3.62 | 0.094 |\n| Hooks                 | 51.85%     | 48.15%                  | -  | -     | -       | -   |\n| Fishing equipment     | Nets       | 71.43%                  | 28.57%      | -0.84 | 0.43 | 0.12    | 1.40 | 0.241 |\n|                       | Spears     | 66.67%                  | 33.33%      | -0.61 | 0.53 | 0.06    | 3.25 | 0.244 |\n|                       | Traps      | 58.62%                  | 41.38%      | -0.27 | 0.76 | 0.26    | 2.18 | 0.201 |\n| Direct Fishing        | 62.50%     | 37.50%                  | -  | -     | -       | -   |\n| Fishing methods       | Trapping   | 55.56%                  | 44.44%      | 0.28 | 1.33 | 0.52    | 3.39 | 0.247 |\n| Pollution             | No         | 100.00%                 | 0.00%       | -  | -     | -       | -   |\n|                       | Yes        | 59.26%                  | 40.74%      | 16.19 | Inf. | -       | Inf. | 0.000*** |\n| Interconnection       | Yes        | 53.03%                  | 46.97%      | 1.79 | 6.04 | 1.51    | 4.63 | 0.004* |\n| Bay                   | 66.67%     | 33.33%                  | -  | -     | -       | -   |\n| Watercourse           | Fishpond   | 46.15%                  | 53.85%      | 0.70 | 2.03 | 0.76    | 3.52 | 0.157 |\n|                       | Fishpond   | 46.15%                  | 53.85%      | 0.70 | 2.03 | 0.76    | 3.52 | 0.157 |\n\n---\n\nTable 6\n\nInventory of fish species currently found in Mwenga territory waterbodies and the ones that were found 15 years ago.\n\n| Fish species | Currently available | Available 15 years ago | Interviewees who reported a decline in the species availability N=75 (%) |\n|--------------|---------------------|------------------------|-----------------------------------------------------------------------|\n| Clarias sp.  | ++                  | ++++                   | 54.7                                                                  |\n| Shwe         | -                   | ++                     | 72                                                                    |\n| Ndomondomo   | -                   | ++                     | 82.7                                                                  |\n| Kambanyoka   | +++                 | ++++                   | 24                                                                    |\n| Tumanga      | ++                  | +++                    | 56                                                                    |\n| Misenge      | +                   | ++                     | 62.7                                                                  |\n| Oreochromis sp. | ++ | ++++++ | 81.3 |\n| Amphilius sp. | - | ++ | 88 |\n| Microctenopoma sp. | - | ++ | 78.7 |\n| Piramboia sp. | + | ++ | 62 |\n| Astatotilapia sp. | - | +++ | 84 |\n| Bitete | - | ++ | 86 |\n| Tonge | + | ++ | 64 |\n| Total number | 7 | 13 | |\n\nLegend: +or – are related to the presence or absence of the specie; +, ++, +++, ++++, ++++, +++++implies the abundance of the fish in natural fish ecosystems. Overall, this study adds weight to others that highlight the negative effect of mining on the aquatic biodiversity (Kitula, 2006, Talukdar et al., 2016, Azevedo-Santos et al., 2021, Simonin et al., 2021), and underscores the urgent need for actions and policies from local authorities to ensure the sustainability of aquatic ecosystems."

In [449]:
import importlib
import functions
importlib.reload(functions)

messages = [{
            "role": "system",
            "content": system_prompt
    }]
    
messages.append({
        "role": "user",
        "content": "Read this mining-impact study carefully: " + markdown_text + "\n\n" + text_prompt
})

stream = ollama.chat(
    model=MODEL_Lang,
    messages=messages,
    stream=True,
    options={"seed":seed,
             #"num_ctx":4096*10,
             #"num_predict":4096*5,
             #"timeout":3600,
             "temperature":0
            },
)

try:
    # Stream the chunks as they arrive
    response = ""
    for chunk in stream:
        # Each chunk is a dict; content lives here:
        if "message" in chunk and "content" in chunk["message"]:
            text = chunk["message"]["content"]
            #print(text, end="", flush=True)   
            response += text    
except Exception as e:
    print(f"Error calling Ollama API: {e}.")
    response = None

# Append assistant response to history
messages.append({
    "role": "assistant",
    "content": response,
})


print("response", response)
        
# # 2. get text response for the metrics (supply extracted tables): 
# response_metrics, messages_metrics = functions.extract_information(ollama, MODEL, SEED, system_prompt, image_paths,
#                                                          prompt = text_prompt_diversity_metrics + "\n\nTables from the text: " + text_tables
#                                                         )

# print("response_metrics", response_metrics)

response **1. Scale**
**Answer:** **Local**
**Reasoning:** The paper investigates the impacts of artisanal small‑scale gold mining on fish biodiversity and water quality in a single territory (Mweso, North Kivu, DRC). It does not aggregate data across multiple regions or countries, nor does it model impacts at a broader scale. Hence it is a case‑study at the local level.

---

**2. Country / Continent**
**Answer:** **Democratic Republic of the Congo (Africa)**
**Reasoning:** All field work, sampling, and questionnaires were carried out in the Mweso territory of North Kivu province, which is located in the Democratic Republic of the Congo (DRC) on the African continent.

---

**3. Specific location**
**Answer:** **Central/Eastern Africa – North Kivu province, Mweso territory (DRC)**
**Reasoning:** The study repeatedly refers to “Mweso territory, North Kivu, DRC” and to the three sampling sites (Mugunga, Nyamuragira, Lukula) that lie within this sub‑regional area.

---

**4. Mined commodities**
**Answer:** **Gold**
**Reasoning:** The manuscript explicitly states that the impacts stem from “artisanal small‑scale gold mining” and discusses “gold extraction” as the driver of contamination. No other commodities are mentioned.

---

**5. Mining stage**
**Answer:** **Operational** (also **Exploration/Pre‑operational** can be inferred, but the study focuses on active mining)
**Reasoning:** The text describes “ongoing artisanal small‑scale gold mining activities” that are currently contaminating water bodies. Therefore the mine is in the operational stage. No indication is given that the site is closed or under rehabilitation.

---

**6. Type of mining activity**
**Answer:** **Artisanal small‑scale mining** (and **placer mining** – inferred from “alluvial gold mining”)
**Reasoning:** The methods and discussion repeatedly refer to “artisanal small‑scale gold mining” and to “alluvial gold mining” (i.e., extraction of gold from river sediments). No mention is made of open‑cut, underground, or other large‑scale techniques, so the most appropriate classification is artisanal small‑scale mining. Because alluvial gold extraction is a form of placer mining, “placer mining” is also applicable. If a strict single‑choice is required, **Artisanal small‑scale mining** is selected; otherwise both are listed.

---

**7. Experimental design**
**Answer:** **Mining area vs non‑mining area**
**Reasoning:** The study compares three sites: two that are impacted by artisanal gold mining (Mugunga and Nyamuragira) and one reference site that is not affected by mining (Lukula). This constitutes a classic “mining area vs non‑mining area” design.

---

**8. Taxonomic groups**
**Answer:** **Freshwater fish (Actinopterygii – families Cyprinidae, Cichlidae, Mormyridae, Clariidae, Schilbeidae, Mochokidae, etc.)**
**Reasoning:** The biodiversity component of the study is limited to fish species. The authors identified 25 fish species belonging to the above families, which are all freshwater teleosts.

---

**9. Biomes of assessment**
**Answer:** **Freshwater**
**Reasoning:** All sampling was performed in streams/rivers (Mugunga, Nyamuragira, Lukula) and the focus is on water‑quality‑driven impacts on fish. No marine, grassland, forest, or other biomes are involved.

---

**10. Method of assessment**
**Answer:** **Interviews and questionnaires + In‑situ sampling + Laboratory analysis + Statistical analysis**
**Reasoning:**
- **Interviews and questionnaires:** A structured questionnaire was administered to 53 fishers to capture their perceptions of changes in fish abundance, diversity, and water quality.
- **In‑situ sampling:** Water samples were collected on‑site at the three study locations.
- **Laboratory analysis:** Physicochemical parameters (pH, temperature, conductivity, TDS, turbidity, dissolved oxygen, nutrients, heavy metals) were measured using laboratory equipment (spectrophotometer, multiparameter probe).
- **Statistical analysis:** The authors performed ANOVA, Tukey HSD, and Principal Component Analysis (PCA) to compare water‑quality variables among sites and to relate them to fishers’ observations.

No spatial modelling or expert‑opinion workshops were reported, so those are marked **NA**.

---

**11. Specific methodology**
**Answer:**

| Step | Description |
|------|-------------|
| **a. Community perception survey** | A semi‑structured questionnaire (see Table 1) was administered to 53 fishers (selected via purposive sampling) to record their observations on (i) changes in fish abundance, (ii) changes in fish species diversity, and (iii) perceived changes in water quality (e.g., “water looks dirty”, “fish are dying”). |
| **b. Site selection** | Three sampling stations were chosen: two mining‑impacted sites (Mugunga and Nyamuragira) located downstream of active artisanal gold‑mining pits, and one reference site (Lukula) with no known mining activity. |
| **c. Water‑quality sampling** | At each station, water was collected in duplicate bottles (500 mL) for physicochemical analysis. In‑situ measurements of temperature, pH, conductivity, dissolved oxygen, and turbidity were taken with a multiparameter probe (e.g., YSI). |
| **d. Laboratory analysis** | Samples were filtered (0.45 µm) and analyzed for nutrients (NH₄⁺, NO₃⁻, PO₄³⁻) using a spectrophotometer (UV‑Vis) and for heavy metals (e.g., Hg, As) using atomic absorption spectroscopy (AAS). |
| **e. Data processing** | Raw values were entered into Microsoft Excel, then imported into R (v4.2) for statistical testing. One‑way ANOVA assessed differences among sites for each water‑quality variable; Tukey HSD identified pairwise differences. |
| **f. Multivariate analysis** | Principal Component Analysis (PCA) was performed on the standardized water‑quality dataset to visualize the overall environmental gradient and to link it with the fishers’ perception scores. |
| **g. Synthesis** | The authors integrated the quantitative water‑quality results with the qualitative perception data to infer indirect impacts of mining on fish biodiversity (e.g., “low dissolved oxygen and high turbidity correspond to fishers reporting reduced catches”). |

---

**12. Temporal scale**
**Answer:** **0** (ongoing) → **NA** (since the study does not give an explicit number of years since contamination began).
**Reasoning:** The manuscript discusses “current” contamination and “ongoing” mining activities but never states how many years have elapsed since mining started. Therefore the temporal scale cannot be assigned to a year‑range category; we flag it as **NA**.

---

**13. Type of impact or pressure**
**Answer:** **Observed impact** (also **Pressure** could be inferred, but the study reports measured changes).
**Reasoning:** The authors present measured differences in water‑quality parameters (e.g., higher turbidity, lower dissolved oxygen) and link these to fishers’ reports of reduced fish abundance and diversity. This constitutes an **observed impact** on the biodiversity indicator (fish state).

---

**14. Impact pathway**
**Answer:** **Ecotoxicity** (also **Land/Seabed use** is not discussed; **Acidification**, **Eutrophication**, **Water depletion**, **Climate change** are not mentioned).
**Reasoning:** The methods explicitly connect mining‑derived contaminants (heavy metals, suspended sediments) to degraded water quality, which is an ecotoxic pathway. The authors discuss “sediment plume”, “heavy‑metal contamination”, and “low dissolved oxygen” as mechanisms harming fish. No other pathways are described, so the appropriate pathway is **Ecotoxicity**.

---

**15. Description of impact or pressure**
**Key phrases extracted from the paper:**

- *“artisanal small‑scale gold mining activities have led to water contamination, increased turbidity, and reduced dissolved oxygen”* (Results, water‑quality section).
- *“fishers reported a noticeable decline in fish abundance and species diversity in the mining‑impacted streams”* (Results, questionnaire).
- *“the pH values were slightly acidic (6.4–6.8) and the conductivity values were high (up to 1 500 µS cm⁻¹), indicating the presence of dissolved ions from mining runoff”* (Water‑quality results).
- *“the PCA showed that sites downstream of mining activities clustered together and were associated with high turbidity and low DO, which corresponded to the fishers’ perception of poor fish catches”* (Statistical analysis).

These excerpts illustrate that the pressure (mining‑derived contaminants) translates into an observed degradation of water quality, which in turn is linked to reduced fish biodiversity (observed impact).

---

**16. Spatial scale**
**Answer:** **NA**
**Reasoning:** The manuscript does not provide explicit distances (e.g., “5 km downstream of the mine”) between the mining pits and the sampling stations. It only mentions that the three sites are “located within the Mweso territory” and that two are “impacted by mining”. Without a quantified distance, the spatial scale cannot be assigned to a distance range, so we flag this as **NA**.

In [448]:
text_prompt

"Thoroughly analyse the attached mining-impact study and create a section for each of the instructions below. Let's think through each task step by step.\n\n\n1. Scale: The scale at which the study is conducted (choose from: local, regional, global). \n- Local: The paper focuses on a case study from a single mine. \n- Regional: This study focuses on a region of the world. This could be subnational (a series of case studies within an area or a region within a country), national (the country level impact from a single country), multinational (an area that exceeds country bounds), or an area in international waters.\n- Global: The study is a global level analysis. \n\n2. Country/Continent: Which country, countries or continent is this study focused?\n\n3. Specific location: Where specifically is the study focused? I.e., Central Africa, Clarion Clipperton Zone, Global, etc.\n\n4. Mined commodities: List all the commodities mined or studied in the study. These can be commodities that are actively being mined or were mined in the past. Example: If the text states that the studied mine is a coal mine, then the commodity is coal. Polymetallic nodules in the CCZ contain: Mn, Cu, Co, Ni. \n\n5. Mining stage: The stage of mining (choose from: mineral occurrences, exploration/pre-operational, operational, closed, rehabilitation). Multiple options may be applicable.  \n- Mineral occurrences: A known commodity is located. This could be any stage of mining (exploration, operational, closed, etc.).\n- Exploration/Pre-operational: A commodity is known to occur, but mining activities have not commenced.\n- Operational: Mining activities are occurring. The mine is active (e.g., production reported).\n- Closed: Mining activities have concluded, the site could be abandoned or rehabilitated/relinquished.\n- Rehabilitation: Treatment or management of land/water disturbed by mining.\nNote: Mining stage may also be operational and/or closed.\n\n6. Type of mining activity (choose from: open cut, underground, mountaintop removal, in-situ leaching, placer mining, dredging, artisanal small-scale mining, nodule mining, sulphide mining, crust mining, quarrying). Multiple options may be applicable. Look for explicit mentions of these activities in the text with regards to the current study, or choose the most applicable. If information on mining activity is not explicitly stated in the study, flag this with ‘NA’.\n\n7. Experimental design: What comparison is made in mining conditions to determine biodiversity impacts? Choose from: Mining area vs non-mining area, current mining vs post-mining, pre-mining vs current mining, pre-mining vs post-mining, pre-mining vs hypothetical mining (multiple options may be applicable).\n- Mining area vs non-mining area: The impacts of mining in a mining area (any stage) are compared to an untouched area not used for mining.\n- Current mining vs post-mining: The impacts of mining in an area currently being mined are compared to a different area that has undergone mining in the past.\n- Pre-mining vs current mining: The impacts of current mining activities are compared to the state of biodiversity before mining commenced in the same site/area.\n- Pre-mining vs post-mining: The impacts of mining on biodiversity are compared between an area that has undergone mining (after operations have ceased) and the same area before mining occurred.\n- Pre-mining vs hypothetical mining: A mining area (pre-operation) is compared to a hypothetical current/post-mining scenario. \n\n8. Taxonomic groups: Which species group/s are investigated in this study? Try to be as specific as possible (i.e., salamanders, skinks), otherwise use broader taxonomic group (e.g., mammals, amphibians, plants, etc.). In the case of forest, the taxonomic group 'plants' is applicable.\n\n9. Biomes of assessment: The biome in which the biodiversity assessment was conducted (choose from: marine, freshwater, grassland, savanna, shrubland, wetlands, rocky areas, caves and subterranean, forest, desert, tundra). Multiple options may be applicable. \n\n10. Method of assessment: What methods are used to determine the impact or pressure on biodiversity from mining? Choose from: Spatial modelling, expert opinion, statistical analysis, in-situ sampling, laboratory experiment, laboratory analysis, interviews and questionnaires (multiple options may be applicable). Pay close attention to the methods section of the paper to answer this.\n- Spatial modelling: A spatial analysis where the mining data is intersected or overlayed with the biodiversity indicator (use of mapping software required for this selection).\n- Expert opinion: The impacts to biodiversity are determined from an expert workshop or from expert judgement.\n- Statistical analysis: Any kind of statistical analysis of quantitative data to estimate mining impacts. \n- In-situ sampling: Sampling is completed in two or more locations, which can be both inside and outside the impacted area, to compare biodiversity values.\n- Laboratory experiment: Experiments are conducted in a laboratory setting to simulate the impacts of mining on biodiversity.\n- Laboratory analysis: A lab setting is used to assess biodiversity data collected from the field and produce results.\n- Interviews and questionnaires: The biodiversity impacts are determined from questionnaires or interviews with individuals from local communities, through their observations of environmental change.\n\n11. Specific methodology: Detail the specific methodology used in the study to quantify the indirect impacts of mining on biodiversity.\n\n12. Temporal scale: Determine if the text mentions the temporal scale of the study in years, specifically the time elapsed since the onset of mining-related pollution or contamination to the current biodiversity assessment. *Only* if this is explicitly mentioned in the text, choose from: 1-5, 5-20, 20-50, 50-100, 100-1000, 1000+ years. Select '0' if impacts are measured for current or ongoing mining activities. If the study does not specify when contamination began, or if the study does not specify the elapsed time since pollution occurred, simply flag this section with NA.\n\n13. Type of impact or pressure: Is a pressure or an impact to biodiversity assessed? Choose from: Pressure, future impact, observed impact. Multiple options may be applicable. \n- Pressure: When mining activities or mineral occurrences occur in the same area as biodiversity but there is no measured change to biodiversity as a result of mining.\n- Future impact: When there is a predicted change to the biodiversity indicator based on observed changes in a sample area, where mining activities have yet to occur.\n- Observed impact: When there is an observed change to the biodiversity indicator from historic or current mining activities as per the pressure-state-response framework.\n\n14. Impact pathway: Is an impact pathway defined in the methods of the study? Choose from: Land/Seabed use, water depletion, ecotoxicity, acidification, climate change, eutrophication. Multiple options may be applicable. \nIf yes, which pathway (select from below)? If no, choose NA.\n- Land/Seabed use: Impact from land use types or impact from seabed use for underwater mining, e.g., habitat loss, fragmentation, conversion, etc.\n- Water depletion: Impact from the use of water, e.g., water scarcity, depletion, etc. \n- Ecotoxicity: Impact from a chemical or physical agent, e.g., sediment plume, water quality, water contamination, etc.\n- Acidification: Impact from acidic pollutants on land and/or in water, e.g., acid mine drainage).\n- Climate change: Impact from increased greenhouse gas emissions, e.g., changing biomes, extreme weather events, heat stress, etc.\n- Eutrophication: Impact from excessive richness of nutrients in the waterbody, e.g., algal blooms.\n                   \n15. Description of impact or pressure: Briefly elaborate on the pressures/impacts identified in the study. Highlight specific phrases in the paper where information is pulled from.\n\n16. Spatial scale: If observed impacts on biodiversity are measured in the study ('Type of impact or pressure' is 'Observed impact'), determine if the spatial scale of the observed impacts is mentioned in the text, specifically the distance (or a distance range) between the mining activity and the impacted sites sampled for biodiversity. *Only* if this is explicitly mentioned in the text, select in which range of distances this falls: 0-1, 1-5, 5-10, 10-20, 20-50, 50-100, 100+ km. If the text provides no information on spatial scale, simply flag this section with NA.\n\nImportant: For any pierce of information, flag it with 'NA' if this information cannot be filled in (e.g., is not explicitly stated in the study).\n\nExplain your reasoning for each section. "

In [240]:
# 1. extract tables from the text, to ensure correct interpretation of results 
print("Extracting tables from the text...")
text_tables, _ = functions.extract_tables(ollama, MODEL, SEED, system_prompt, extracted_text, image_paths)

Extracting tables from the text...

In [248]:
df

Empty DataFrame
Columns: [Scale, Country/Continent, Specific location, Mined commodities, Mining stage, Type of mining activity, Experimental design, Taxonomic groups, Biomes of assessment, Method of assessment, Specific methodology, Temporal scale, Type of impact or pressure, Impact pathway, Description of impact or pressure, Spatial scale, Metric, Metric category, Impact direction, Significance, P-value, Response study, Response metrics, Extracted tables, Study ID]
Index: []

In [251]:
print(text_tables)

TABLE 1. Average Physicochemical Measures of Sampling Sites within the Finniss River in (a) 1992 and (b) 1995

| site | dist., km | depth, m | pH | cond., mS/cm | turb., NTU | temp., °C | D.O. % sat. |
|------|-----------|----------|----|--------------|------------|-----------|-------------|
| (a) 1992 | | | | | | | |
| 6 | -18 | 1.7 | 7.1 | 0.11 | 4.2 | 21.4 | 50 |
| 5 | -0.1 | 1.4 | 6.9 | 0.11 | 3.0 | 18.9 | 20 |
| 3a | 3 | 2.1 | 6.7 | 0.15 | 3.3 | 20.8 | 22 |
| 2b | 13 | 1.4 | 7.5 | 0.15 | 3.7 | 24.2 | 66 |
| 2a | 15 | 2.8 | 6.9 | 0.14 | 3.0 | 24.0 | 62 |
| 1 | 30 | 3.6 | 5.2 | 0.01 | 0.9 | 23.5 | 59 |
| (b) 1995 | | | | | | | |
| 6 | -18 | 2.2 | 7.5 | 0.33 | 1.7 | 22.2 | 44 |
| 5 | -0.1 | 1.5 | 7.3 | 0.38 | 2.5 | 21.4 | 19 |
| 4 | 1 | 1.7 | 7.5 | 0.37 | 2.5 | 21.9 | 43 |
| 3 | 3 | 2.4 | 7.2 | 0.37 | 2.7 | 21.2 | 34 |
| 2 | 15 | 2.3 | 7.4 | 0.27 | 4.5 | 23.2 | 53 |
| 1 | 30 | 3.9 | 5.8 | 0.02 | 1.8 | 22.9 | 58 |

a Distance (dist) refers to kilometers downstream of the EB confluence. b Dissolved oxygen values consistently declined from the surface. Refer to the text.

TABLE 2. Average Metal Concentrations in Water (ug/L; except Mn, Ca, and Mg in mg/L) Measured at Sampling Sites in (a) 1973, (b) 1974, (c) 1992, and (d) 1995

| site | dist, km | Co | Ni | Cu | Zn | Mn | Ca | Mg |
|------|----------|----|----|----|----|----|----|----|
| (a) 1973 | | | | | | | | |
| 6 | -18 | 2 | 3 | 2 | 2 | 0.002 | 14 | 14 |
| 5 | -0.1 | 20 | 20 | 38 | 15 | 0.015 | 15 | 18 |
| 4 | 1 | 1670 | 2147 | 13403 | 198 | 3.970 | 59 | 27 |
| 3 | 3 | 13 | 38 | 25 | 266 | 0.054 | 16 | 11 |
| 2 | 15 | 15 | 5 | 20 | 55 | 0.050 | 9 | 7 |
| 1 | 30 | 30 | 13 | 20 | 58 | 0.043 | 5 | 4 |
| (b) 1974 | | | | | | | | |
| 6 | -18 | 6 | 16 | 13 | 3 | 0.019 | 21 | 29 |
| 5 | -0.1 | 15 | 12 | 13 | 15 | 0.033 | 18 | 28 |
| 4 | 1 | 90 | 45 | 260 | 75 | 0.425 | 18 | 29 |
| 3 | 3 | 87 | 103 | 259 | 158 | 0.210 | 20 | 30 |
| 2 | 15 | 18 | 21 | 45 | 6 | 0.090 | 17 | 33 |
| 1 | 30 | 8 | 15 | 16 | 29 | 0.065 | 5 | 11 |
| (c) 1992 | | | | | | | | |
| 6 | -18 | 0.3 | 5 | 3 | 8 | 0.025 | 7 | 10 |
| 5 | -0.1 | 1 | 13 | 5 | 6 | 0.064 | 7 | 10 |
| 3a | 3 | 5 | 10 | 27 | 12 | 0.149 | 9 | 16 |
| 2b | 13 | 4 | 11 | 13 | 9 | 0.095 | 7 | 16 |
| 2a | 15 | 3 | 11 | 17 | 0.092 | 8 | 14 |
| 1 | 30 | 2 | 6 | 6 | 7 | 0.037 | 0.3 | 0.5 |
| (d) 1995 | | | | | | | | |
| 6 | -18 | 0.4 | 2 | 1 | 0.007 | 22 | 31 |
| 5 | -0.1 | 0.6 | 2 | 2 | 0.021 | 18 | 38 |
| 4 | 1 | 0.5 | 5 | 4 | 0.005 | 24 | 39 |
| 3 | 3 | 1.1 | 5 | 7 | 0.003 | 18 | 38 |
| 2 | 15 | 0.2 | 3 | 3 | 0.0004 | 16 | 26 |
| 1 | 30 | 0.8 | 4 | 3 | 0.021 | 1 | 1.4 |

a "Less than" values, for some sites prior to remediation, were assigned half the detection limit for the purposes of calculating averages. Zinc was measured in 1995, but obviously inconsistent results were obtained and hence the data were excluded.

TABLE 3. Total Metal Concentrations in Sediment Sampled from the Finniss River in 1996 (µg/g DW)

| dist., km | Mn | Co | Ni | Cu | Zn | Cd | Ba | Pb | U | Fe |
|-----------|----|----|----|----|----|----|----|----|----|----|
| -18 | 101 | 5 | 5 | 17 | lld | 0.05 | 58 | 16 | 4 | 5454 |
| -0.2 | 230 | 11 | 5 | 30 | lld | 0.04 | 65 | 15 | 2 | 9221 |
| 4 | 582 | 269 | 371 | 3643 | 1896 | 0.30 | 76 | 127 | 129 | 12284 |
| 8 | 209 | 193 | 191 | 1061 | 1748 | 0.35 | 84 | 138 | 45 | 8426 |
| 11 | 551 | 202 | 98 | 404 | 112 | 0.22 | 58 | 37 | 17 | 10510 |

a Downstream of the East Branch confluence. b lld; less than the limit of detection.

TABLE 4. Numbers of Fishes Sampled at Each Site during (a) Three Periods Prior to Mine-Site Remediation and (b) Two Periods Postremediation

(a) Three Periods Prior to Mine-Site Remediation

| species | 1 | 2 | 3 | 4 | 5 | 6 | 1 | 2 | 3 | 4 | 5 | 6 | 1 | 2 | 1 | 4 | 5 | 6 |
|---------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| Nematalosa | 54 | 1 | 0 | 0 | 32 | 35 | 78 | 5 | 0 | 2 | 39 | 6 | 69 | 0 | 0 | 23 | 0 | 0 |
| Neosilurus | 24 | 0 | 0 | 0 | 14 | 21 | 49 | 0 | 0 | 0 | 16 | 20 | 24 | 2 | 0 | 0 | 16 | 2 |
| Toxotes | 1 | 0 | 0 | 0 | 17 | 4 | 0 | 0 | 0 | 0 | 4 | 1 | 0 | 0 | 0 | 0 | 1 | 1 |
| Megalops | 30 | 29 | 0 | 5 | 30 | 24 | 45 | 17 | 0 | 6 | 16 | 6 | 5 | 5 | 3 | 4 | 11 | 2 |
| Amniataba | 12 | 0 | 0 | 0 | 13 | 3 | 12 | 0 | 0 | 0 | 3 | 1 | 2 | 0 | 0 | 0 | 2 | 0 |
| Black bream | 6 | 0 | 0 | 2 | 5 | 25 | 2 | 0 | 0 | 1 | 3 | 13 | 2 | 0 | 0 | 0 | 3 | 2 |
| Melanotaenia | 0 | 0 | 20 | 21 | 2 | 0 | 1 | 0 | 2 | 6 | 1 | 1 | 0 | 0 | 2 | 6 | 0 | 3 |
| sample no. | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 |

(b) Two Periods Postremediation

| species | 1 | 2a | 2b | 3a | 5 | 6 | 1 | 2 | 3 | 4 | 5 | 6 |
|---------|---|----|----|----|---|---|---|---|---|---|---|---|
| Nematalosa | 184 | 976 | 196 | 216 | 0 | 342 | 172 | 512 | 692 | 162 | 130 | 388 |
| Neosilurus | 12 | 34 | 16 | 30 | 12 | 98 | 26 | 22 | 20 | 8 | 20 | 106 |
| Toxotes | 10 | 14 | 0 | 0 | 0 | 2 | 2 | 28 | 26 | 0 | 0 | 0 |
| Megalops | 30 | 54 | 28 | 32 | 60 | 19 | 54 | 28 | 86 | 62 | 12 | 28 |
| Amniataba | 0 | 2 | 0 | 2 | 0 | 5 | 8 | 8 | 0 | 8 | 0 | 4 |
| Black bream | 0 | 0 | 0 | 2 | 0 | 4 | 2 | 6 | 0 | 0 | 0 | 0 |
| Melanotaenia | 8 | 12 | 12 | 2 | 0 | 0 | 0 | 2 | 2 | 2 | 0 | 0 |
| sample no. | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 |

a Values adjusted to equivalent catch effort.

TABLE 5. Fishes Recovered Moribund or Dead in the Finniss River Downstream of the Confluence with the East Branch Following Its First Flush, over Two Preremedial Periods of Observation

| species | 1973/1974 | 1974/1975 |
|---------|-----------|-----------|
| Amniataba | + | + |
| Leiotherapon | + |  |
| Megalops | + | + |
| Melanotaenia | + | + |
| Neosilurus | + | + |

TABLE 6. Average Abundances of Fish Taxa and Their Percentage Contribution to Average Dissimilarity Measures between Samples from Preremedial Impacted Sites and All Other Samples

| species | av abundances impacted, preremedial sites | av abundances all other sites | % contribution to av dissimilarity |
|---------|---------------------------------------|-----------------------------|--------------------------------|
| Nematalosa | 3.1 | 216 | 28.2 |
| Neosilurus | 1.4 | 30.3 | 20.7 |
| Amniataba | 0.0 | 4.3 | 11.3 |
| Megalops | 12.9 | 30.3 | 10.8 |
| Toxotes | 0.0 | 5.8 | 10.0 |
| Black bream | 0.3 | 3.8 | 9.6 |
| Melanotaenia | 5.7 | 2.4 | 9.5 |